# coding: utf-8

# flake8: noqa
"""
    Events

    Events can be used to let you know when something happens in your organization. Every happening in your organization will be recorded as a new Event. For example, when a new payment is received, we will create a <code>payment_thankyou</code> event; when a subscription is created, we will create a <code>subscription_created</code> event.<br/> <br/>You can retrieve these events individually or as a <a href=\"https://www.zoho.com/billing/api/v1/events/#list-of-events\">list</a> using our API. If you want to update the data on your server when an event occurs, you can use webhooks to send these event objects directly to an endpoint on your application’s server. Learn more about <a href=\"https://www.zoho.com/billing/help/settings/automation.html\">webhooks</a>.<br/><br/>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from ls_zoho_billing_events.models.event_response import EventResponse
from ls_zoho_billing_events.models.event_response_webhooks_inner import EventResponseWebhooksInner
from ls_zoho_billing_events.models.list_of_events_response import ListOfEventsResponse
from ls_zoho_billing_events.models.list_of_events_response_events_inner import ListOfEventsResponseEventsInner
from ls_zoho_billing_events.models.retrieve_an_event_response import RetrieveAnEventResponse
