# coding: utf-8

"""
    Tasks

    A project comprises of a single or multiple tasks that need to be completed. You need to add a task to the project before you log time.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_tasks.models.get_a_task_response_task import GetATaskResponseTask

class TestGetATaskResponseTask(unittest.TestCase):
    """GetATaskResponseTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetATaskResponseTask:
        """Test GetATaskResponseTask
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetATaskResponseTask`
        """
        model = GetATaskResponseTask()
        if include_optional:
            return GetATaskResponseTask(
                project_id = '90300000072369',
                project_name = 'Furniture Manufacturing',
                task_id = '90300000072369',
                task_name = 'Painting',
                description = '',
                rate = 3,
                status = 'active',
                is_billable = True
            )
        else:
            return GetATaskResponseTask(
        )
        """

    def testGetATaskResponseTask(self):
        """Test GetATaskResponseTask"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
