# coding: utf-8

"""
    Cards

    A card object shows the credit card information for a particular customer

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_cards.models.list_all_active_credit_cards_of_a_customer_response import ListAllActiveCreditCardsOfACustomerResponse

class TestListAllActiveCreditCardsOfACustomerResponse(unittest.TestCase):
    """ListAllActiveCreditCardsOfACustomerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllActiveCreditCardsOfACustomerResponse:
        """Test ListAllActiveCreditCardsOfACustomerResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllActiveCreditCardsOfACustomerResponse`
        """
        model = ListAllActiveCreditCardsOfACustomerResponse()
        if include_optional:
            return ListAllActiveCreditCardsOfACustomerResponse(
                code = 0,
                message = 'success',
                cards = [
                    ls_zoho_billing_cards.models.list_all_active_credit_cards_of_a_customer_response_cards_inner.list_all_active_credit_cards_of_a_customer_response_cards_inner(
                        card_id = '90300000079226', 
                        customer_id = '9030000005664', 
                        status = 'active', 
                        last_four_digits = 2145, 
                        expiry_month = 9, 
                        expiry_year = 2030, 
                        payment_gateway = 'payflow_pro', 
                        created_time = '2016-06-05T12:30:08-0700', 
                        updated_time = '2016-06-05T02:30:08-0700', )
                    ]
            )
        else:
            return ListAllActiveCreditCardsOfACustomerResponse(
        )
        """

    def testListAllActiveCreditCardsOfACustomerResponse(self):
        """Test ListAllActiveCreditCardsOfACustomerResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
