# coding: utf-8

"""
    Time Entries

    Time entries are various entries of time made by users in a project, based on the time they spent on a project, in a task.<br><br><b>Possible error codes: </b><br><table><thead><tr><th>Error Code</th><th>Message</th></tr></thead><tbody><tr><td><span style=\"color:#FF0000;\"> 1002</span></td><td>This task does not exist in this project. Hence, this timesheet entry cannot be made</td></tr><tr><td><span style=\"color:#FF0000;\"> 20050</span></td><td>This timesheet entry is already being timed</td></tr><tr><td><span style=\"color:#FF0000;\"> 20054</span></td><td>This timesheet is being timed. Hence, it cannot be edited</td></tr></tbody></table>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "ls_zoho_billing_time_entries"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Time Entries",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="https://www.theletstream.com?utm_source&#x3D;github-zohobillingclient",
    keywords=["OpenAPI", "OpenAPI-Generator", "Time Entries"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Time entries are various entries of time made by users in a project, based on the time they spent on a project, in a task.&lt;br&gt;&lt;br&gt;&lt;b&gt;Possible error codes: &lt;/b&gt;&lt;br&gt;&lt;table&gt;&lt;thead&gt;&lt;tr&gt;&lt;th&gt;Error Code&lt;/th&gt;&lt;th&gt;Message&lt;/th&gt;&lt;/tr&gt;&lt;/thead&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td&gt;&lt;span style&#x3D;\&quot;color:#FF0000;\&quot;&gt; 1002&lt;/span&gt;&lt;/td&gt;&lt;td&gt;This task does not exist in this project. Hence, this timesheet entry cannot be made&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;span style&#x3D;\&quot;color:#FF0000;\&quot;&gt; 20050&lt;/span&gt;&lt;/td&gt;&lt;td&gt;This timesheet entry is already being timed&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;span style&#x3D;\&quot;color:#FF0000;\&quot;&gt; 20054&lt;/span&gt;&lt;/td&gt;&lt;td&gt;This timesheet is being timed. Hence, it cannot be edited&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;
    """,  # noqa: E501
    package_data={"ls_zoho_billing_time_entries": ["py.typed"]},
)