# coding: utf-8

"""
    Events

    Events can be used to let you know when something happens in your organization. Every happening in your organization will be recorded as a new Event. For example, when a new payment is received, we will create a <code>payment_thankyou</code> event; when a subscription is created, we will create a <code>subscription_created</code> event.<br/> <br/>You can retrieve these events individually or as a <a href=\"https://www.zoho.com/billing/api/v1/events/#list-of-events\">list</a> using our API. If you want to update the data on your server when an event occurs, you can use webhooks to send these event objects directly to an endpoint on your application’s server. Learn more about <a href=\"https://www.zoho.com/billing/help/settings/automation.html\">webhooks</a>.<br/><br/>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "ls_zoho_billing_events"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Events",
    author='Letstream',
    author_email='support@theletstream.com',
    url="https://www.theletstream.com?utm_source&#x3D;github-zohobillingclient",
    keywords=["OpenAPI", "OpenAPI-Generator", "Events"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Events can be used to let you know when something happens in your organization. Every happening in your organization will be recorded as a new Event. For example, when a new payment is received, we will create a &lt;code&gt;payment_thankyou&lt;/code&gt; event; when a subscription is created, we will create a &lt;code&gt;subscription_created&lt;/code&gt; event.&lt;br/&gt; &lt;br/&gt;You can retrieve these events individually or as a &lt;a href&#x3D;\&quot;https://www.zoho.com/billing/api/v1/events/#list-of-events\&quot;&gt;list&lt;/a&gt; using our API. If you want to update the data on your server when an event occurs, you can use webhooks to send these event objects directly to an endpoint on your application’s server. Learn more about &lt;a href&#x3D;\&quot;https://www.zoho.com/billing/help/settings/automation.html\&quot;&gt;webhooks&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
    """,  # noqa: E501
    package_data={"ls_zoho_billing_events": ["py.typed"]},
)