# coding: utf-8

"""
    Subscriptions

    A subscription enables you to charge customers at specified intervals for a plan of their choice.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from ls_zoho_billing_subscription.models.item_custom_fields_inner import ItemCustomFieldsInner
from ls_zoho_billing_subscription.models.tags_inner import TagsInner
from typing import Optional, Set
from typing_extensions import Self

class BuyOneTimeAddonResponseInvoiceInvoiceItemsInner(BaseModel):
    """
    BuyOneTimeAddonResponseInvoiceInvoiceItemsInner
    """ # noqa: E501
    item_id: Optional[StrictStr] = Field(default=None, description="The ID of the item included in the invoice.")
    name: Optional[StrictStr] = Field(default=None, description="Name generated by concatenation of the product name and the selected plan.")
    description: Optional[Any] = Field(default=None, description="Small description about the Invoice item.")
    code: Optional[StrictStr] = Field(default=None, description="Item code of the item included in the invoice.")
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Price of a plan for a particular subscription. If a value is provided here, the plan’s price for this subscription will be changed to the given value. If no value is provided, the plan’s price would be the same as what it was when it was created.")
    quantity: Optional[StrictInt] = Field(default=None, description="Required quantity of the chosen plan.")
    tags: Optional[List[TagsInner]] = None
    item_custom_fields: Optional[List[ItemCustomFieldsInner]] = Field(default=None, description="Custom fields for a item.")
    discount_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The discount amount included in an invoice on applying a coupon.")
    item_total: Optional[StrictInt] = Field(default=None, description="Cost of an item included in the invoice. This would be the product of quantity of the item included and the price of that item.")
    __properties: ClassVar[List[str]] = ["item_id", "name", "description", "code", "price", "quantity", "tags", "item_custom_fields", "discount_amount", "item_total"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BuyOneTimeAddonResponseInvoiceInvoiceItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in item_custom_fields (list)
        _items = []
        if self.item_custom_fields:
            for _item_item_custom_fields in self.item_custom_fields:
                if _item_item_custom_fields:
                    _items.append(_item_item_custom_fields.to_dict())
            _dict['item_custom_fields'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BuyOneTimeAddonResponseInvoiceInvoiceItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "item_id": obj.get("item_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "code": obj.get("code"),
            "price": obj.get("price"),
            "quantity": obj.get("quantity"),
            "tags": [TagsInner.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "item_custom_fields": [ItemCustomFieldsInner.from_dict(_item) for _item in obj["item_custom_fields"]] if obj.get("item_custom_fields") is not None else None,
            "discount_amount": obj.get("discount_amount"),
            "item_total": obj.get("item_total")
        })
        return _obj


