# coding: utf-8

"""
    Subscriptions

    A subscription enables you to charge customers at specified intervals for a plan of their choice.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ShippingAddress(BaseModel):
    """
    Customer's shipping address object. It contains <code>attention</code>, <code>street</code>, <code>city</code>, <code>state</code>,<code>zip</code>, <code>country</code> and <code>fax</code>.
    """ # noqa: E501
    attention: Optional[StrictStr] = Field(default=None, description="Attention of the customer’s shipping address.")
    street: Optional[StrictStr] = Field(default=None, description="Street of the customer’s shipping address.")
    city: Optional[StrictStr] = Field(default=None, description="City of the customer’s shipping address.")
    state: Optional[StrictStr] = Field(default=None, description="State of the customer’s shipping address.")
    zip: Optional[StrictStr] = Field(default=None, description="Zip code of the customer’s shipping address.")
    country: Optional[StrictStr] = Field(default=None, description="Country of the customer’s shipping address.")
    fax: Optional[StrictStr] = Field(default=None, description="Fax number of the customer’s shipping address.")
    __properties: ClassVar[List[str]] = ["attention", "street", "city", "state", "zip", "country", "fax"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ShippingAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ShippingAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attention": obj.get("attention"),
            "street": obj.get("street"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "zip": obj.get("zip"),
            "country": obj.get("country"),
            "fax": obj.get("fax")
        })
        return _obj


