# coding: utf-8

"""
    Customers

    A customer object allows you to keep track of all customer related information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from ls_zoho_billing_customers.models.billing_address import BillingAddress
from ls_zoho_billing_customers.models.customer_response_documents_inner import CustomerResponseDocumentsInner
from ls_zoho_billing_customers.models.customer_response_tags_inner import CustomerResponseTagsInner
from ls_zoho_billing_customers.models.shipping_address import ShippingAddress
from ls_zoho_billing_customers.models.update_a_customer_request_custom_fields_inner import UpdateACustomerRequestCustomFieldsInner
from ls_zoho_billing_customers.models.update_a_customer_response_customer_default_templates_inner import UpdateACustomerResponseCustomerDefaultTemplatesInner
from typing import Optional, Set
from typing_extensions import Self

class UpdateACustomerResponseCustomer(BaseModel):
    """
    UpdateACustomerResponseCustomer
    """ # noqa: E501
    customer_id: Optional[StrictStr] = Field(default=None, description="Unique ID generated by the server. This is used as identifier.")
    display_name: Optional[StrictStr] = Field(default=None, description="Name of the customer which will be displayed in the interface and invoices.")
    salutation: Optional[StrictStr] = Field(default=None, description="Salutation of the customer.")
    first_name: Optional[StrictStr] = Field(default=None, description="First name of the customer.")
    last_name: Optional[StrictStr] = Field(default=None, description="Last name of the customer.")
    email: Optional[StrictStr] = Field(default=None, description="Email address of the customer.")
    tags: Optional[List[CustomerResponseTagsInner]] = None
    company_name: Optional[StrictStr] = Field(default=None, description="Registered name of the company the customer represents.")
    phone: Optional[StrictStr] = Field(default=None, description="Customer's landline or fixed-line number.")
    mobile: Optional[StrictStr] = Field(default=None, description="Customer's mobile phone number.")
    website: Optional[StrictStr] = Field(default=None, description="Customer's website if any.")
    department: Optional[StrictStr] = Field(default=None, description="Customer's department.")
    designation: Optional[StrictStr] = Field(default=None, description="Customer's designation.")
    is_portal_enabled: Optional[StrictBool] = Field(default=None, description="Is Client portal enabled for the customer.")
    billing_address: Optional[BillingAddress] = None
    shipping_address: Optional[ShippingAddress] = None
    currency_code: Optional[StrictStr] = Field(default='currency_code chosen in organization profile settings', description="Currency code of the currency in which the customer wants to pay. If currency_code is not specified here, the currency chosen in your Zoho Billing organization will be used for billing.")
    currency_id: Optional[StrictStr] = Field(default=None, description="Currency ID of the customer's currency.")
    ach_supported: Optional[StrictBool] = Field(default=False, description="Set to true if ACH payment is supported for the customer.")
    price_precision: Optional[StrictInt] = Field(default=None, description="The Price Precision of the selected currency for the customer")
    unused_credits: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Customer's unused credits.")
    outstanding: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Amount that has to be paid to the customer.")
    notes: Optional[StrictStr] = Field(default=None, description="A short note about the customer.")
    status: Optional[StrictStr] = Field(default=None, description="Status of the customer. It can either be <code>active</code> or <code>inactive</code>.")
    custom_fields: Optional[List[UpdateACustomerRequestCustomFieldsInner]] = Field(default=None, description="Additional fields for customers.")
    zcrm_account_id: Optional[StrictStr] = Field(default=None, description="This is the Zoho CRM account id of the customer if the customer is synced with the accounts in Zoho CRM.")
    zcrm_contact_id: Optional[StrictStr] = Field(default=None, description="This is the Zoho CRM contact id of the customer if the customer is synced with the contacts in Zoho CRM.")
    updated_time: Optional[StrictStr] = Field(default=None, description="Time at which the customer details were last updated.")
    created_time: Optional[StrictStr] = Field(default=None, description="Time at which the customer was created.")
    source: Optional[StrictStr] = Field(default=None, description="Denotes how the customer was created.")
    payment_terms_label: Optional[StrictStr] = Field(default=None, description="Text field of payment terms.")
    is_linked_with_zohocrm: Optional[StrictBool] = Field(default=None, description="Set to true if linked with Zoho CRM.")
    primary_contactperson_id: Optional[StrictStr] = Field(default=None, description="Unique Id of primary contact person. This ID will refer to contactperson_id for this customer.")
    can_add_card: Optional[StrictBool] = Field(default=None, description="Set to true if card can be associated.")
    can_add_bank_account: Optional[StrictBool] = Field(default=None, description="Set to true if bank account can be associated.")
    default_templates: Optional[List[UpdateACustomerResponseCustomerDefaultTemplatesInner]] = Field(default=None, description="Default templates associated with the customer.")
    documents: Optional[List[CustomerResponseDocumentsInner]] = Field(default=None, description="List of files attached to a particular customer.")
    __properties: ClassVar[List[str]] = ["customer_id", "display_name", "salutation", "first_name", "last_name", "email", "tags", "company_name", "phone", "mobile", "website", "department", "designation", "is_portal_enabled", "billing_address", "shipping_address", "currency_code", "currency_id", "ach_supported", "price_precision", "unused_credits", "outstanding", "notes", "status", "custom_fields", "zcrm_account_id", "zcrm_contact_id", "updated_time", "created_time", "source", "payment_terms_label", "is_linked_with_zohocrm", "primary_contactperson_id", "can_add_card", "can_add_bank_account", "default_templates", "documents"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateACustomerResponseCustomer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of billing_address
        if self.billing_address:
            _dict['billing_address'] = self.billing_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipping_address
        if self.shipping_address:
            _dict['shipping_address'] = self.shipping_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in custom_fields (list)
        _items = []
        if self.custom_fields:
            for _item_custom_fields in self.custom_fields:
                if _item_custom_fields:
                    _items.append(_item_custom_fields.to_dict())
            _dict['custom_fields'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in default_templates (list)
        _items = []
        if self.default_templates:
            for _item_default_templates in self.default_templates:
                if _item_default_templates:
                    _items.append(_item_default_templates.to_dict())
            _dict['default_templates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in documents (list)
        _items = []
        if self.documents:
            for _item_documents in self.documents:
                if _item_documents:
                    _items.append(_item_documents.to_dict())
            _dict['documents'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateACustomerResponseCustomer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customer_id": obj.get("customer_id"),
            "display_name": obj.get("display_name"),
            "salutation": obj.get("salutation"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "email": obj.get("email"),
            "tags": [CustomerResponseTagsInner.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "company_name": obj.get("company_name"),
            "phone": obj.get("phone"),
            "mobile": obj.get("mobile"),
            "website": obj.get("website"),
            "department": obj.get("department"),
            "designation": obj.get("designation"),
            "is_portal_enabled": obj.get("is_portal_enabled"),
            "billing_address": BillingAddress.from_dict(obj["billing_address"]) if obj.get("billing_address") is not None else None,
            "shipping_address": ShippingAddress.from_dict(obj["shipping_address"]) if obj.get("shipping_address") is not None else None,
            "currency_code": obj.get("currency_code") if obj.get("currency_code") is not None else 'currency_code chosen in organization profile settings',
            "currency_id": obj.get("currency_id"),
            "ach_supported": obj.get("ach_supported") if obj.get("ach_supported") is not None else False,
            "price_precision": obj.get("price_precision"),
            "unused_credits": obj.get("unused_credits"),
            "outstanding": obj.get("outstanding"),
            "notes": obj.get("notes"),
            "status": obj.get("status"),
            "custom_fields": [UpdateACustomerRequestCustomFieldsInner.from_dict(_item) for _item in obj["custom_fields"]] if obj.get("custom_fields") is not None else None,
            "zcrm_account_id": obj.get("zcrm_account_id"),
            "zcrm_contact_id": obj.get("zcrm_contact_id"),
            "updated_time": obj.get("updated_time"),
            "created_time": obj.get("created_time"),
            "source": obj.get("source"),
            "payment_terms_label": obj.get("payment_terms_label"),
            "is_linked_with_zohocrm": obj.get("is_linked_with_zohocrm"),
            "primary_contactperson_id": obj.get("primary_contactperson_id"),
            "can_add_card": obj.get("can_add_card"),
            "can_add_bank_account": obj.get("can_add_bank_account"),
            "default_templates": [UpdateACustomerResponseCustomerDefaultTemplatesInner.from_dict(_item) for _item in obj["default_templates"]] if obj.get("default_templates") is not None else None,
            "documents": [CustomerResponseDocumentsInner.from_dict(_item) for _item in obj["documents"]] if obj.get("documents") is not None else None
        })
        return _obj


