# coding: utf-8

"""
    Settings

    Tax Settings Related APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_settings.models.retrieve_list_of_tax_exemptions_response import RetrieveListOfTaxExemptionsResponse

class TestRetrieveListOfTaxExemptionsResponse(unittest.TestCase):
    """RetrieveListOfTaxExemptionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveListOfTaxExemptionsResponse:
        """Test RetrieveListOfTaxExemptionsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveListOfTaxExemptionsResponse`
        """
        model = RetrieveListOfTaxExemptionsResponse()
        if include_optional:
            return RetrieveListOfTaxExemptionsResponse(
                code = 0,
                message = 'success',
                tax_exemptions = [
                    ls_zoho_billing_settings.models.retrieve_list_of_tax_exemptions_response_tax_exemptions_inner.retrieve_list_of_tax_exemptions_response_tax_exemptions_inner(
                        description = 'Non-Profit Organization', 
                        tax_exemption_id = '903000006345', 
                        tax_exemption_code = 'GST FREE', 
                        type = 'customer', )
                    ]
            )
        else:
            return RetrieveListOfTaxExemptionsResponse(
        )
        """

    def testRetrieveListOfTaxExemptionsResponse(self):
        """Test RetrieveListOfTaxExemptionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
