# coding: utf-8

"""
    Invoices

    Invoices describe how much a customer owes for his subscription. Invoices are created for recurring charges, one time charges including any prorated adjustments.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from ls_zoho_billing_invoices.models.apply_credits_request_apply_creditnotes_inner import ApplyCreditsRequestApplyCreditnotesInner
from ls_zoho_billing_invoices.models.apply_credits_request_invoice_payments_inner import ApplyCreditsRequestInvoicePaymentsInner
from typing import Optional, Set
from typing_extensions import Self

class ApplyCreditsRequest(BaseModel):
    """
    ApplyCreditsRequest
    """ # noqa: E501
    invoice_payments: Optional[List[ApplyCreditsRequestInvoicePaymentsInner]] = Field(default=None, description="Payments applied to an invoice.")
    apply_creditnotes: Optional[List[ApplyCreditsRequestApplyCreditnotesInner]] = Field(default=None, description="Credits applied to invoice.")
    __properties: ClassVar[List[str]] = ["invoice_payments", "apply_creditnotes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplyCreditsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in invoice_payments (list)
        _items = []
        if self.invoice_payments:
            for _item_invoice_payments in self.invoice_payments:
                if _item_invoice_payments:
                    _items.append(_item_invoice_payments.to_dict())
            _dict['invoice_payments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in apply_creditnotes (list)
        _items = []
        if self.apply_creditnotes:
            for _item_apply_creditnotes in self.apply_creditnotes:
                if _item_apply_creditnotes:
                    _items.append(_item_apply_creditnotes.to_dict())
            _dict['apply_creditnotes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplyCreditsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "invoice_payments": [ApplyCreditsRequestInvoicePaymentsInner.from_dict(_item) for _item in obj["invoice_payments"]] if obj.get("invoice_payments") is not None else None,
            "apply_creditnotes": [ApplyCreditsRequestApplyCreditnotesInner.from_dict(_item) for _item in obj["apply_creditnotes"]] if obj.get("apply_creditnotes") is not None else None
        })
        return _obj


