# coding: utf-8

"""
    Invoices

    Invoices describe how much a customer owes for his subscription. Invoices are created for recurring charges, one time charges including any prorated adjustments.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CollectChargeViaBankAccountCreditCardResponsePaymentInvoicesInner(BaseModel):
    """
    CollectChargeViaBankAccountCreditCardResponsePaymentInvoicesInner
    """ # noqa: E501
    invoice_id: Optional[StrictStr] = Field(default=None, description="Unique ID generated for an invoice.")
    invoice_number: Optional[StrictStr] = Field(default=None, description="Unique ID (starts with INV) of an invoice.")
    var_date: Optional[Any] = Field(default=None, description="Date on which the invoice was raised.", alias="date")
    invoice_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Total amount raised for the invoice.")
    amount_applied: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Amount paid for the invoice.")
    balance_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unpaid amount of the invoice.")
    __properties: ClassVar[List[str]] = ["invoice_id", "invoice_number", "date", "invoice_amount", "amount_applied", "balance_amount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CollectChargeViaBankAccountCreditCardResponsePaymentInvoicesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if var_date (nullable) is None
        # and model_fields_set contains the field
        if self.var_date is None and "var_date" in self.model_fields_set:
            _dict['date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CollectChargeViaBankAccountCreditCardResponsePaymentInvoicesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "invoice_id": obj.get("invoice_id"),
            "invoice_number": obj.get("invoice_number"),
            "date": obj.get("date"),
            "invoice_amount": obj.get("invoice_amount"),
            "amount_applied": obj.get("amount_applied"),
            "balance_amount": obj.get("balance_amount")
        })
        return _obj


