# coding: utf-8

"""
    Invoices

    Invoices describe how much a customer owes for his subscription. Invoices are created for recurring charges, one time charges including any prorated adjustments.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetInvoiceEmailContentResponseDataFromEmailsInner(BaseModel):
    """
    GetInvoiceEmailContentResponseDataFromEmailsInner
    """ # noqa: E501
    user_name: Optional[StrictStr] = Field(default=None, description="User name of the contact")
    selected: Optional[StrictBool] = Field(default=None, description="To check if invoice is selected or not")
    email: Optional[StrictStr] = Field(default=None, description="Email address of the customer.")
    organization_contact_id: Optional[StrictStr] = Field(default=None, description="ID of the contact's organisation")
    is_org_email_id: Optional[StrictBool] = Field(default=None, description="To check if the email ID belongs to the organisation")
    __properties: ClassVar[List[str]] = ["user_name", "selected", "email", "organization_contact_id", "is_org_email_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetInvoiceEmailContentResponseDataFromEmailsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetInvoiceEmailContentResponseDataFromEmailsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_name": obj.get("user_name"),
            "selected": obj.get("selected"),
            "email": obj.get("email"),
            "organization_contact_id": obj.get("organization_contact_id"),
            "is_org_email_id": obj.get("is_org_email_id")
        })
        return _obj


