# coding: utf-8

"""
    Customers

    A customer object allows you to keep track of all customer related information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_customers.models.create_a_customer_request_custom_fields_inner import CreateACustomerRequestCustomFieldsInner

class TestCreateACustomerRequestCustomFieldsInner(unittest.TestCase):
    """CreateACustomerRequestCustomFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateACustomerRequestCustomFieldsInner:
        """Test CreateACustomerRequestCustomFieldsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateACustomerRequestCustomFieldsInner`
        """
        model = CreateACustomerRequestCustomFieldsInner()
        if include_optional:
            return CreateACustomerRequestCustomFieldsInner(
                label = 'label',
                value = '129890'
            )
        else:
            return CreateACustomerRequestCustomFieldsInner(
        )
        """

    def testCreateACustomerRequestCustomFieldsInner(self):
        """Test CreateACustomerRequestCustomFieldsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
