# coding: utf-8

# flake8: noqa

"""
    Projects

    A project is a series of tasks performed over a period of time, to achieve certain targets. There can be many number of people working on a single project and a project may consist of single or multiple tasks. A project is billed and charged upon a customer whom the project was taken up for.<br><br><b>Possible error codes: </b><br><table><thead><tr><th>Error Code</th><th>Message</th></tr></thead><tbody><tr><td><span style=\"color:#FF0000;\"> 1002</span></td><td>Project does not exists</td></tr><tr><td><span style=\"color:#FF0000;\"> 20004</span></td><td>Please ensure that the amount is not negative</td></tr><tr><td><span style=\"color:#FF0000;\"> 20077</span></td><td>Expense has been recorded for this project. Hence, it cannot be deleted</td></tr></tbody></table></tbody></table>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ProjectsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ActivateAProjectResponse",
    "AssignUsersRequest",
    "AssignUsersResponse",
    "AssignUsersResponseUsersInner",
    "CloneAProjectRequest",
    "CloneAProjectResponse",
    "CreateAProjectRequest",
    "CreateAProjectRequestTasksInner",
    "CreateAProjectRequestUsersInner",
    "CreateAProjectResponse",
    "DeactivateAProjectResponse",
    "DeleteCommentResponse",
    "DeleteProjectResponse",
    "DeleteUserResponse",
    "GetAProjectResponse",
    "GetAProjectResponseProject",
    "GetAUserResponse",
    "GetAUserResponseUsers",
    "InviteUserRequest",
    "InviteUserResponse",
    "InviteUserResponseUsersInner",
    "ListCommentsResponse",
    "ListCommentsResponseCommentsInner",
    "ListInvoicesResponse",
    "ListInvoicesResponseInvoicesInner",
    "ListProjectsResponse",
    "ListProjectsResponseProjectsInner",
    "ListUsersResponse",
    "PostCommentRequest",
    "PostCommentResponse",
    "PostCommentResponseCommentsInner",
    "ProjectResponse",
    "ProjectResponseTasksInner",
    "ProjectResponseUsersInner",
    "UpdateAProjectRequest",
    "UpdateAProjectResponse",
    "UpdateAProjectResponseProject",
    "UpdateUserRequest",
    "UpdateUserResponse",
]

# import apis into sdk package
from ls_zoho_billing_projects.api.projects_api import ProjectsApi as ProjectsApi

# import ApiClient
from ls_zoho_billing_projects.api_response import ApiResponse as ApiResponse
from ls_zoho_billing_projects.api_client import ApiClient as ApiClient
from ls_zoho_billing_projects.configuration import Configuration as Configuration
from ls_zoho_billing_projects.exceptions import OpenApiException as OpenApiException
from ls_zoho_billing_projects.exceptions import ApiTypeError as ApiTypeError
from ls_zoho_billing_projects.exceptions import ApiValueError as ApiValueError
from ls_zoho_billing_projects.exceptions import ApiKeyError as ApiKeyError
from ls_zoho_billing_projects.exceptions import ApiAttributeError as ApiAttributeError
from ls_zoho_billing_projects.exceptions import ApiException as ApiException

# import models into sdk package
from ls_zoho_billing_projects.models.activate_a_project_response import ActivateAProjectResponse as ActivateAProjectResponse
from ls_zoho_billing_projects.models.assign_users_request import AssignUsersRequest as AssignUsersRequest
from ls_zoho_billing_projects.models.assign_users_response import AssignUsersResponse as AssignUsersResponse
from ls_zoho_billing_projects.models.assign_users_response_users_inner import AssignUsersResponseUsersInner as AssignUsersResponseUsersInner
from ls_zoho_billing_projects.models.clone_a_project_request import CloneAProjectRequest as CloneAProjectRequest
from ls_zoho_billing_projects.models.clone_a_project_response import CloneAProjectResponse as CloneAProjectResponse
from ls_zoho_billing_projects.models.create_a_project_request import CreateAProjectRequest as CreateAProjectRequest
from ls_zoho_billing_projects.models.create_a_project_request_tasks_inner import CreateAProjectRequestTasksInner as CreateAProjectRequestTasksInner
from ls_zoho_billing_projects.models.create_a_project_request_users_inner import CreateAProjectRequestUsersInner as CreateAProjectRequestUsersInner
from ls_zoho_billing_projects.models.create_a_project_response import CreateAProjectResponse as CreateAProjectResponse
from ls_zoho_billing_projects.models.deactivate_a_project_response import DeactivateAProjectResponse as DeactivateAProjectResponse
from ls_zoho_billing_projects.models.delete_comment_response import DeleteCommentResponse as DeleteCommentResponse
from ls_zoho_billing_projects.models.delete_project_response import DeleteProjectResponse as DeleteProjectResponse
from ls_zoho_billing_projects.models.delete_user_response import DeleteUserResponse as DeleteUserResponse
from ls_zoho_billing_projects.models.get_a_project_response import GetAProjectResponse as GetAProjectResponse
from ls_zoho_billing_projects.models.get_a_project_response_project import GetAProjectResponseProject as GetAProjectResponseProject
from ls_zoho_billing_projects.models.get_a_user_response import GetAUserResponse as GetAUserResponse
from ls_zoho_billing_projects.models.get_a_user_response_users import GetAUserResponseUsers as GetAUserResponseUsers
from ls_zoho_billing_projects.models.invite_user_request import InviteUserRequest as InviteUserRequest
from ls_zoho_billing_projects.models.invite_user_response import InviteUserResponse as InviteUserResponse
from ls_zoho_billing_projects.models.invite_user_response_users_inner import InviteUserResponseUsersInner as InviteUserResponseUsersInner
from ls_zoho_billing_projects.models.list_comments_response import ListCommentsResponse as ListCommentsResponse
from ls_zoho_billing_projects.models.list_comments_response_comments_inner import ListCommentsResponseCommentsInner as ListCommentsResponseCommentsInner
from ls_zoho_billing_projects.models.list_invoices_response import ListInvoicesResponse as ListInvoicesResponse
from ls_zoho_billing_projects.models.list_invoices_response_invoices_inner import ListInvoicesResponseInvoicesInner as ListInvoicesResponseInvoicesInner
from ls_zoho_billing_projects.models.list_projects_response import ListProjectsResponse as ListProjectsResponse
from ls_zoho_billing_projects.models.list_projects_response_projects_inner import ListProjectsResponseProjectsInner as ListProjectsResponseProjectsInner
from ls_zoho_billing_projects.models.list_users_response import ListUsersResponse as ListUsersResponse
from ls_zoho_billing_projects.models.post_comment_request import PostCommentRequest as PostCommentRequest
from ls_zoho_billing_projects.models.post_comment_response import PostCommentResponse as PostCommentResponse
from ls_zoho_billing_projects.models.post_comment_response_comments_inner import PostCommentResponseCommentsInner as PostCommentResponseCommentsInner
from ls_zoho_billing_projects.models.project_response import ProjectResponse as ProjectResponse
from ls_zoho_billing_projects.models.project_response_tasks_inner import ProjectResponseTasksInner as ProjectResponseTasksInner
from ls_zoho_billing_projects.models.project_response_users_inner import ProjectResponseUsersInner as ProjectResponseUsersInner
from ls_zoho_billing_projects.models.update_a_project_request import UpdateAProjectRequest as UpdateAProjectRequest
from ls_zoho_billing_projects.models.update_a_project_response import UpdateAProjectResponse as UpdateAProjectResponse
from ls_zoho_billing_projects.models.update_a_project_response_project import UpdateAProjectResponseProject as UpdateAProjectResponseProject
from ls_zoho_billing_projects.models.update_user_request import UpdateUserRequest as UpdateUserRequest
from ls_zoho_billing_projects.models.update_user_response import UpdateUserResponse as UpdateUserResponse
