# coding: utf-8

"""
    Recurring Expenses

    Recurring expenses are those expenses that repeat itself after a fixed interval of time.<br><br><b>Possible error codes: </b><br><table><thead><tr><th>Error Code</th><th>Message</th></tr></thead><tbody><tr><td><span style=\"color:#FF0000;\"> 4027</span></td><td>Please select a valid date range</td></tr><tr><td><span style=\"color:#FF0000;\"> 5012</span></td><td>Recurrence Name already exists</td></tr><tr><td><span style=\"color:#FF0000;\"> 5015</span></td><td>Enter a valid expense amount</td></tr></tbody></table>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "ls_zoho_billing_recurring_expenses"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Recurring Expenses",
    author='Letstream',
    author_email='support@theletstream.com',
    url="https://www.theletstream.com?utm_source&#x3D;github-zohobillingclient",
    keywords=["OpenAPI", "OpenAPI-Generator", "Recurring Expenses"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Recurring expenses are those expenses that repeat itself after a fixed interval of time.&lt;br&gt;&lt;br&gt;&lt;b&gt;Possible error codes: &lt;/b&gt;&lt;br&gt;&lt;table&gt;&lt;thead&gt;&lt;tr&gt;&lt;th&gt;Error Code&lt;/th&gt;&lt;th&gt;Message&lt;/th&gt;&lt;/tr&gt;&lt;/thead&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td&gt;&lt;span style&#x3D;\&quot;color:#FF0000;\&quot;&gt; 4027&lt;/span&gt;&lt;/td&gt;&lt;td&gt;Please select a valid date range&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;span style&#x3D;\&quot;color:#FF0000;\&quot;&gt; 5012&lt;/span&gt;&lt;/td&gt;&lt;td&gt;Recurrence Name already exists&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;span style&#x3D;\&quot;color:#FF0000;\&quot;&gt; 5015&lt;/span&gt;&lt;/td&gt;&lt;td&gt;Enter a valid expense amount&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;
    """,  # noqa: E501
    package_data={"ls_zoho_billing_recurring_expenses": ["py.typed"]},
)