# coding: utf-8

"""
    Recurring Expenses

    Recurring expenses are those expenses that repeat itself after a fixed interval of time.<br><br><b>Possible error codes: </b><br><table><thead><tr><th>Error Code</th><th>Message</th></tr></thead><tbody><tr><td><span style=\"color:#FF0000;\"> 4027</span></td><td>Please select a valid date range</td></tr><tr><td><span style=\"color:#FF0000;\"> 5012</span></td><td>Recurrence Name already exists</td></tr><tr><td><span style=\"color:#FF0000;\"> 5015</span></td><td>Enter a valid expense amount</td></tr></tbody></table>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_recurring_expenses.models.recurring_expense_response_line_item import RecurringExpenseResponseLineItem

class TestRecurringExpenseResponseLineItem(unittest.TestCase):
    """RecurringExpenseResponseLineItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecurringExpenseResponseLineItem:
        """Test RecurringExpenseResponseLineItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecurringExpenseResponseLineItem`
        """
        model = RecurringExpenseResponseLineItem()
        if include_optional:
            return RecurringExpenseResponseLineItem(
                line_item_id = '10763000000140068',
                account_id = '982000000561057',
                account_name = 'Rent',
                description = ' ',
                tax_amount = 11.85,
                tax_id = '982000000566007',
                tax_name = 'SalesTax',
                tax_type = 'tax',
                tax_percentage = 10.5,
                item_total = '100',
                item_order = '1',
                hsn_or_sac = '80540',
                reverse_charge_tax_id = '982000000567254',
                reverse_charge_tax_name = 'inter',
                reverse_charge_tax_percentage = 10,
                reverse_charge_tax_amount = 10
            )
        else:
            return RecurringExpenseResponseLineItem(
        )
        """

    def testRecurringExpenseResponseLineItem(self):
        """Test RecurringExpenseResponseLineItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
