# coding: utf-8

"""
    Items

    A product is the item offered for sale. It can be a commodity. Based on the type of your business, you can offer one or more goods.<br><br><b>Possible error codes: </b><br><table><thead><tr><th>Error Code</th><th>Message</th></tr></thead><tbody><tr><td><span style=\"color:#FF0000;\"> 1000</span></td><td>The item name already exist</td></tr><tr><tr><td><span style=\"color:#FF0000;\"> 2006</span></td><td>Item does not exist</td></tr><td><span style=\"color:#FF0000;\"> 2049</span></td><td>Items which are a part of other transactions cannot be deleted. Instead, mark them as inactive</td></tr><tr><td><span style=\"color:#FF0000;\"> 2076</span></td><td>Product type cannot be changed for Items having transactions</td></tr></tbody></table>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "ls_zoho_billing_items"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Items",
    author='Letstream',
    author_email='support@theletstream.com',
    url="https://www.theletstream.com?utm_source&#x3D;github-zohobillingclient",
    keywords=["OpenAPI", "OpenAPI-Generator", "Items"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    A product is the item offered for sale. It can be a commodity. Based on the type of your business, you can offer one or more goods.&lt;br&gt;&lt;br&gt;&lt;b&gt;Possible error codes: &lt;/b&gt;&lt;br&gt;&lt;table&gt;&lt;thead&gt;&lt;tr&gt;&lt;th&gt;Error Code&lt;/th&gt;&lt;th&gt;Message&lt;/th&gt;&lt;/tr&gt;&lt;/thead&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td&gt;&lt;span style&#x3D;\&quot;color:#FF0000;\&quot;&gt; 1000&lt;/span&gt;&lt;/td&gt;&lt;td&gt;The item name already exist&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;tr&gt;&lt;td&gt;&lt;span style&#x3D;\&quot;color:#FF0000;\&quot;&gt; 2006&lt;/span&gt;&lt;/td&gt;&lt;td&gt;Item does not exist&lt;/td&gt;&lt;/tr&gt;&lt;td&gt;&lt;span style&#x3D;\&quot;color:#FF0000;\&quot;&gt; 2049&lt;/span&gt;&lt;/td&gt;&lt;td&gt;Items which are a part of other transactions cannot be deleted. Instead, mark them as inactive&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;&lt;span style&#x3D;\&quot;color:#FF0000;\&quot;&gt; 2076&lt;/span&gt;&lt;/td&gt;&lt;td&gt;Product type cannot be changed for Items having transactions&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;
    """,  # noqa: E501
    package_data={"ls_zoho_billing_items": ["py.typed"]},
)