# coding: utf-8

"""
    Subscriptions

    A subscription enables you to charge customers at specified intervals for a plan of their choice.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_subscription.models.create_a_subscription_request_customer_custom_fields_inner import CreateASubscriptionRequestCustomerCustomFieldsInner

class TestCreateASubscriptionRequestCustomerCustomFieldsInner(unittest.TestCase):
    """CreateASubscriptionRequestCustomerCustomFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateASubscriptionRequestCustomerCustomFieldsInner:
        """Test CreateASubscriptionRequestCustomerCustomFieldsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateASubscriptionRequestCustomerCustomFieldsInner`
        """
        model = CreateASubscriptionRequestCustomerCustomFieldsInner()
        if include_optional:
            return CreateASubscriptionRequestCustomerCustomFieldsInner(
                label = '',
                value = ''
            )
        else:
            return CreateASubscriptionRequestCustomerCustomFieldsInner(
                label = '',
                value = '',
        )
        """

    def testCreateASubscriptionRequestCustomerCustomFieldsInner(self):
        """Test CreateASubscriptionRequestCustomerCustomFieldsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
