# coding: utf-8

"""
    Subscriptions

    A subscription enables you to charge customers at specified intervals for a plan of their choice.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_subscription.models.reactivate_subscription_response import ReactivateSubscriptionResponse

class TestReactivateSubscriptionResponse(unittest.TestCase):
    """ReactivateSubscriptionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReactivateSubscriptionResponse:
        """Test ReactivateSubscriptionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReactivateSubscriptionResponse`
        """
        model = ReactivateSubscriptionResponse()
        if include_optional:
            return ReactivateSubscriptionResponse(
                code = 0,
                message = 'Subscription has been reactivated successfully.',
                subscription = ls_zoho_billing_subscription.models.reactivate_subscription_response_subscription.reactivate_subscription_response_subscription(
                    subscription_id = '90300000079200', 
                    name = 'GatorHost-Basic', 
                    status = 'live', 
                    amount = 50, 
                    created_at = '2016-06-11', 
                    activated_at = '2016-06-15', 
                    current_term_starts_at = '2016-06-05', 
                    current_term_ends_at = '2016-06-05', 
                    last_billing_at = '2016-06-05', 
                    next_billing_at = '2016-06-30', 
                    expires_at = '2016-06-05', 
                    interval = '1', 
                    interval_unit = 'months', 
                    auto_collect = True, 
                    created_time = '2016-06-11T17:57:13-0700', 
                    updated_time = '2016-06-04T16:44:15-0700', 
                    reference_id = 'bowmanfurniture', 
                    salesperson_id = '903000000058001', 
                    salesperson_name = 'Franklin', 
                    child_invoice_id = '90300000079210', 
                    currency_code = 'USD', 
                    currency_symbol = '$', 
                    end_of_term = False, 
                    product_id = '90300000079065', 
                    product_name = 'Bowman Furniture', 
                    plan = ls_zoho_billing_subscription.models.reactivate_subscription_response_subscription_plan.reactivate_subscription_response_subscription_plan(
                        plan_code = 'basic-monthly', 
                        quantity = 1, 
                        price = 50, 
                        tags = [
                            ls_zoho_billing_subscription.models.tags_inner.tags_inner(
                                tag_id = 56, 
                                tag_option_id = 56, )
                            ], 
                        item_custom_fields = [
                            ls_zoho_billing_subscription.models.item_custom_fields_inner.item_custom_fields_inner(
                                label = '', 
                                value = '', )
                            ], 
                        discount = 20, 
                        total = 50, 
                        setup_fee = 20, 
                        plan_description = 'Monthly Basic plan', 
                        billing_cycles = -1, 
                        trial_days = 0, ), 
                    addons = [
                        ls_zoho_billing_subscription.models.reactivate_subscription_response_subscription_addons_inner.reactivate_subscription_response_subscription_addons_inner(
                            addon_code = 'Email-basic', 
                            addon_description = 'Monthly addon.', )
                        ], 
                    coupon = ls_zoho_billing_subscription.models.subscription_response_coupon.subscription_response_coupon(
                        coupon_code = 'Flat10', 
                        discount_amount = 44, ), 
                    card = ls_zoho_billing_subscription.models.update_a_subscription_response_subscription_card.update_a_subscription_response_subscription_card(
                        card_id = 90300000079226, 
                        last_four_digits = 2145, 
                        payment_gateway = 'payflow_pro', 
                        expiry_month = 9, 
                        expiry_year = 2030, ), 
                    payment_terms = 0, 
                    payment_terms_label = 'Due On Receipt', 
                    can_add_bank_account = True, 
                    customer = ls_zoho_billing_subscription.models.retrieve_a_subscription_response_subscription_customer.retrieve_a_subscription_response_subscription_customer(
                        customer_id = 903000000000099, 
                        display_name = 'Bowman Furniture', 
                        first_name = 'Benjamin', 
                        last_name = 'George', 
                        email = 'benjamin.george@bowmanfurniture.com', 
                        company_name = 'Bowman Furniture', 
                        billing_address = ls_zoho_billing_subscription.models.billing_address.billing_address(
                            attention = 'Benjamin George', 
                            street = 'Harrington Bay Street', 
                            city = 'Salt Lake City', 
                            state = 'CA', 
                            country = 'U.S.A', 
                            zip = '92612', 
                            fax = '4527389', ), 
                        shipping_address = ls_zoho_billing_subscription.models.shipping_address.shipping_address(
                            attention = 'Benjamin George', 
                            street = 'Harrington Bay Street', 
                            city = 'Salt Lake City', 
                            state = 'CA', 
                            zip = '92612', 
                            country = 'U.S.A', 
                            fax = '4527389', ), ), 
                    custom_fields = [
                        ls_zoho_billing_subscription.models.subscription_response_custom_fields_inner.subscription_response_custom_fields_inner(
                            index = 1, 
                            data_type = 'text', )
                        ], 
                    taxes = [
                        ls_zoho_billing_subscription.models.subscription_response_taxes_inner.subscription_response_taxes_inner(
                            tax_id = '903000002345', 
                            tax_name = 'GST', 
                            tax_amount = '2.50', )
                        ], 
                    contactpersons = [
                        ls_zoho_billing_subscription.models.subscription_response_contactpersons_inner.subscription_response_contactpersons_inner(
                            contactperson_id = '903000000000099', )
                        ], 
                    notes = [
                        ls_zoho_billing_subscription.models.reactivate_subscription_response_subscription_notes_inner.reactivate_subscription_response_subscription_notes_inner(
                            note_id = '903000076543', 
                            description = '', 
                            commented_by = 'Benjamin', 
                            commented_time = '2016-06-11T17:57:13-0700', )
                        ], 
                    payment_gateways = [
                        ls_zoho_billing_subscription.models.subscription_response_payment_gateways_inner.subscription_response_payment_gateways_inner()
                        ], )
            )
        else:
            return ReactivateSubscriptionResponse(
        )
        """

    def testReactivateSubscriptionResponse(self):
        """Test ReactivateSubscriptionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
