# coding: utf-8

"""
    Subscriptions

    A subscription enables you to charge customers at specified intervals for a plan of their choice.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_subscription.models.comments_inner import CommentsInner

class TestCommentsInner(unittest.TestCase):
    """CommentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommentsInner:
        """Test CommentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommentsInner`
        """
        model = CommentsInner()
        if include_optional:
            return CommentsInner(
                comment_id = '90300000003133',
                description = Invoice has been marked as void,
                commented_by_id = '90300000002099',
                commented_by = 'Benjamin',
                comment_type = 'system',
                var_date = None,
                time = '2016-06-11T17:57:13-0700',
                operation_type = 'add',
                transaction_id = '9030000079467',
                transaction_type = invoice
            )
        else:
            return CommentsInner(
        )
        """

    def testCommentsInner(self):
        """Test CommentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
