# coding: utf-8

"""
    Subscriptions

    A subscription enables you to charge customers at specified intervals for a plan of their choice.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_subscription.models.buy_one_time_addon_response_invoice import BuyOneTimeAddonResponseInvoice

class TestBuyOneTimeAddonResponseInvoice(unittest.TestCase):
    """BuyOneTimeAddonResponseInvoice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuyOneTimeAddonResponseInvoice:
        """Test BuyOneTimeAddonResponseInvoice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuyOneTimeAddonResponseInvoice`
        """
        model = BuyOneTimeAddonResponseInvoice()
        if include_optional:
            return BuyOneTimeAddonResponseInvoice(
                invoice_id = '9030000079426',
                number = 'INV-384',
                status = 'live',
                invoice_date = '2016-06-15',
                due_date = '2016-06-15',
                payment_expected_date = '10-05-2016',
                ach_payment_initiated = True,
                invoice_items = [
                    ls_zoho_billing_subscription.models.buy_one_time_addon_response_invoice_invoice_items_inner.buy_one_time_addon_response_invoice_invoice_items_inner(
                        item_id = '90300000079434', 
                        name = 'GatorHost-Basic', 
                        description = One time addon purchased, 
                        code = 'basic-monthly', 
                        price = 50, 
                        quantity = 1, 
                        tags = [
                            ls_zoho_billing_subscription.models.tags_inner.tags_inner(
                                tag_id = 56, 
                                tag_option_id = 56, )
                            ], 
                        item_custom_fields = [
                            ls_zoho_billing_subscription.models.item_custom_fields_inner.item_custom_fields_inner(
                                label = '', 
                                value = '', )
                            ], 
                        discount_amount = 44, 
                        item_total = 50, )
                    ],
                transaction_type = 'invoice',
                customer_id = '903000000000099',
                customer_name = 'Benjamin',
                email = 'benjamin.george@bowmanfurniture.com',
                total = 50,
                payment_made = 370,
                balance = 0,
                coupons = [
                    ls_zoho_billing_subscription.models.buy_one_time_addon_response_invoice_coupons_inner.buy_one_time_addon_response_invoice_coupons_inner(
                        coupon_code = 'Flat10', 
                        coupon_name = 'Flat 10', 
                        discount_amount = 44, )
                    ],
                credits_applied = 0,
                credits = [
                    ls_zoho_billing_subscription.models.buy_one_time_addon_response_invoice_credits_inner.buy_one_time_addon_response_invoice_credits_inner(
                        creditnote_id = '9030000079876', 
                        creditnotes_number = 'CN-26', 
                        credited_date = '2016-06-15', 
                        credited_amount = '15', )
                    ],
                taxes = [
                    ls_zoho_billing_subscription.models.subscription_response_taxes_inner.subscription_response_taxes_inner(
                        tax_id = '903000002345', 
                        tax_name = 'GST', 
                        tax_amount = '2.50', )
                    ],
                custom_fields = [
                    ls_zoho_billing_subscription.models.subscription_response_custom_fields_inner.subscription_response_custom_fields_inner(
                        index = 1, 
                        label = '', 
                        value = '', 
                        data_type = 'text', )
                    ],
                salesperson_id = '903000000058001',
                salesperson_name = 'Franklin',
                write_off_amount = 0,
                payments = [
                    ls_zoho_billing_subscription.models.buy_one_time_addon_response_invoice_payments_inner.buy_one_time_addon_response_invoice_payments_inner(
                        payment_id = '90300000079467', 
                        payment_mode = 'autotransaction', 
                        invoice_payment_id = '9030000079469', 
                        gateway_transaction_id = '9030000056453', 
                        description = '', 
                        date = '2016-06-15', 
                        reference_number = 'INV-384', 
                        amount = 50, 
                        exchange_rate = 2, )
                    ],
                currency_code = 'USD',
                currency_symbol = '$',
                created_time = '2016-06-11T17:57:13-0700',
                updated_time = '2016-06-04T16:44:15-0700',
                billing_address = ls_zoho_billing_subscription.models.billing_address.billing_address(
                    attention = 'Benjamin George', 
                    street = 'Harrington Bay Street', 
                    city = 'Salt Lake City', 
                    state = 'CA', 
                    country = 'U.S.A', 
                    zip = '92612', 
                    fax = '4527389', ),
                shipping_address = ls_zoho_billing_subscription.models.shipping_address.shipping_address(
                    attention = 'Benjamin George', 
                    street = 'Harrington Bay Street', 
                    city = 'Salt Lake City', 
                    state = 'CA', 
                    zip = '92612', 
                    country = 'U.S.A', 
                    fax = '4527389', ),
                comments = [
                    ls_zoho_billing_subscription.models.buy_one_time_addon_response_invoice_comments_inner.buy_one_time_addon_response_invoice_comments_inner(
                        comment_id = '90300000003133', 
                        description = Invoice has been marked as void, 
                        commented_by_id = '90300000002099', 
                        commented_by = null, 
                        comment_type = 'system', 
                        date = null, 
                        time = '2016-06-11T17:57:13-0700', 
                        operation_type = 'add', 
                        transaction_id = '9030000079467', 
                        transaction_type = 'invoice', )
                    ]
            )
        else:
            return BuyOneTimeAddonResponseInvoice(
        )
        """

    def testBuyOneTimeAddonResponseInvoice(self):
        """Test BuyOneTimeAddonResponseInvoice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
