# coding: utf-8

"""
    Subscriptions

    A subscription enables you to charge customers at specified intervals for a plan of their choice.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_subscription.models.create_a_subscription_request_plan import CreateASubscriptionRequestPlan

class TestCreateASubscriptionRequestPlan(unittest.TestCase):
    """CreateASubscriptionRequestPlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateASubscriptionRequestPlan:
        """Test CreateASubscriptionRequestPlan
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateASubscriptionRequestPlan`
        """
        model = CreateASubscriptionRequestPlan()
        if include_optional:
            return CreateASubscriptionRequestPlan(
                plan_code = 'basic-monthly',
                plan_description = 'Monthly Basic plan',
                price = 50,
                setup_fee = 20,
                setup_fee_tax_id = '9030000123123',
                tags = [
                    ls_zoho_billing_subscription.models.tags_inner.tags_inner(
                        tag_id = 56, 
                        tag_option_id = 56, )
                    ],
                item_custom_fields = [
                    ls_zoho_billing_subscription.models.item_custom_fields_inner.item_custom_fields_inner(
                        label = '', 
                        value = '', )
                    ],
                quantity = 1,
                tax_id = None,
                tax_exemption_id = '903000006345',
                tax_exemption_code = 'GST FREE',
                tds_tax_id = '982000000557012',
                sat_item_key_code = '71121206',
                unitkey_code = 'E48',
                setup_fee_tax_exemption_id = '9030000123098',
                setup_fee_tax_exemption_code = 'GST FREE',
                exclude_trial = False,
                exclude_setup_fee = False,
                billing_cycles = -1,
                trial_days = 0
            )
        else:
            return CreateASubscriptionRequestPlan(
                plan_code = 'basic-monthly',
                tax_id = None,
        )
        """

    def testCreateASubscriptionRequestPlan(self):
        """Test CreateASubscriptionRequestPlan"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
