# coding: utf-8

"""
    Subscriptions

    A subscription enables you to charge customers at specified intervals for a plan of their choice.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_subscription.models.add_charge_request import AddChargeRequest

class TestAddChargeRequest(unittest.TestCase):
    """AddChargeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddChargeRequest:
        """Test AddChargeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddChargeRequest`
        """
        model = AddChargeRequest()
        if include_optional:
            return AddChargeRequest(
                amount = 50,
                description = Charges for Additional usage,
                tags = [
                    ls_zoho_billing_subscription.models.tags_inner.tags_inner(
                        tag_id = 56, 
                        tag_option_id = 56, )
                    ],
                item_custom_fields = [
                    ls_zoho_billing_subscription.models.item_custom_fields_inner.item_custom_fields_inner(
                        label = '', 
                        value = '', )
                    ],
                account_id = '90300000791111',
                add_to_unbilled_charges = True
            )
        else:
            return AddChargeRequest(
                amount = 50,
        )
        """

    def testAddChargeRequest(self):
        """Test AddChargeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
