# coding: utf-8

"""
    Subscriptions

    A subscription enables you to charge customers at specified intervals for a plan of their choice.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_subscription.models.update_custom_fields_response import UpdateCustomFieldsResponse

class TestUpdateCustomFieldsResponse(unittest.TestCase):
    """UpdateCustomFieldsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCustomFieldsResponse:
        """Test UpdateCustomFieldsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCustomFieldsResponse`
        """
        model = UpdateCustomFieldsResponse()
        if include_optional:
            return UpdateCustomFieldsResponse(
                code = 0,
                message = 'Custom Fields Updated Successfully.',
                data = ls_zoho_billing_subscription.models.update_custom_fields_response_data.update_custom_fields_response_data(
                    index = 1, 
                    value = '', 
                    label = '', 
                    data_type = 'text', 
                    customfield_id = '9030000089798', )
            )
        else:
            return UpdateCustomFieldsResponse(
        )
        """

    def testUpdateCustomFieldsResponse(self):
        """Test UpdateCustomFieldsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
