# coding: utf-8

"""
    Subscriptions

    A subscription enables you to charge customers at specified intervals for a plan of their choice.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_subscription.models.add_charge_response_invoice_comments_inner import AddChargeResponseInvoiceCommentsInner

class TestAddChargeResponseInvoiceCommentsInner(unittest.TestCase):
    """AddChargeResponseInvoiceCommentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddChargeResponseInvoiceCommentsInner:
        """Test AddChargeResponseInvoiceCommentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddChargeResponseInvoiceCommentsInner`
        """
        model = AddChargeResponseInvoiceCommentsInner()
        if include_optional:
            return AddChargeResponseInvoiceCommentsInner(
                comment_id = '90300000003133',
                description = Invoice created from subscription - GatorHost-Basic.,
                commented_by_id = '90300000002099',
                commented_by = None,
                comment_type = 'system',
                var_date = None,
                time = '2016-06-11T17:57:13-0700',
                operation_type = 'add',
                transaction_id = '9030000079467',
                transaction_type = 'invoice'
            )
        else:
            return AddChargeResponseInvoiceCommentsInner(
        )
        """

    def testAddChargeResponseInvoiceCommentsInner(self):
        """Test AddChargeResponseInvoiceCommentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
