# coding: utf-8

"""
    Invoices

    Invoices describe how much a customer owes for his subscription. Invoices are created for recurring charges, one time charges including any prorated adjustments.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_invoices.models.get_invoice_email_content_response_data_to_contacts_inner import GetInvoiceEmailContentResponseDataToContactsInner

class TestGetInvoiceEmailContentResponseDataToContactsInner(unittest.TestCase):
    """GetInvoiceEmailContentResponseDataToContactsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetInvoiceEmailContentResponseDataToContactsInner:
        """Test GetInvoiceEmailContentResponseDataToContactsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetInvoiceEmailContentResponseDataToContactsInner`
        """
        model = GetInvoiceEmailContentResponseDataToContactsInner()
        if include_optional:
            return GetInvoiceEmailContentResponseDataToContactsInner(
                first_name = 'David',
                selected = True,
                phone = '+1-925-921-9201',
                email = 'benjamin.george@bowmanfurniture.com',
                last_name = 'Sujin',
                salutation = 'Mr',
                contact_person_id = '982000000567003',
                mobile = '+1-4054439562'
            )
        else:
            return GetInvoiceEmailContentResponseDataToContactsInner(
        )
        """

    def testGetInvoiceEmailContentResponseDataToContactsInner(self):
        """Test GetInvoiceEmailContentResponseDataToContactsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
