# coding: utf-8

"""
    Invoices

    Invoices describe how much a customer owes for his subscription. Invoices are created for recurring charges, one time charges including any prorated adjustments.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_invoices.models.update_address_request import UpdateAddressRequest

class TestUpdateAddressRequest(unittest.TestCase):
    """UpdateAddressRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAddressRequest:
        """Test UpdateAddressRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAddressRequest`
        """
        model = UpdateAddressRequest()
        if include_optional:
            return UpdateAddressRequest(
                billing_address = ls_zoho_billing_invoices.models.retrieve_an_invoice_response_invoice_billing_address.retrieve_an_invoice_response_invoice_billing_address(
                    city = 'Salt Lake City', 
                    state = 'CA', 
                    zip = '92612', 
                    country = 'U.S.A', 
                    fax = '4527389', ),
                shipping_address = ls_zoho_billing_invoices.models.shipping_address.shipping_address(
                    street = 'Harrington Bay Street', 
                    city = 'Salt Lake City', 
                    state = 'CA', 
                    zip = '92612', 
                    country = 'U.S.A', 
                    fax = '4527389', )
            )
        else:
            return UpdateAddressRequest(
        )
        """

    def testUpdateAddressRequest(self):
        """Test UpdateAddressRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
