# coding: utf-8

"""
    Invoices

    Invoices describe how much a customer owes for his subscription. Invoices are created for recurring charges, one time charges including any prorated adjustments.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_invoices.models.update_an_invoice_customfield_response import UpdateAnInvoiceCustomfieldResponse

class TestUpdateAnInvoiceCustomfieldResponse(unittest.TestCase):
    """UpdateAnInvoiceCustomfieldResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAnInvoiceCustomfieldResponse:
        """Test UpdateAnInvoiceCustomfieldResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAnInvoiceCustomfieldResponse`
        """
        model = UpdateAnInvoiceCustomfieldResponse()
        if include_optional:
            return UpdateAnInvoiceCustomfieldResponse(
                code = 0,
                message = 'Custom Fields Updated Successfully'
            )
        else:
            return UpdateAnInvoiceCustomfieldResponse(
        )
        """

    def testUpdateAnInvoiceCustomfieldResponse(self):
        """Test UpdateAnInvoiceCustomfieldResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
