# coding: utf-8

"""
    Invoices

    Invoices describe how much a customer owes for his subscription. Invoices are created for recurring charges, one time charges including any prorated adjustments.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_invoices.models.list_invoice_comments_and_history_response import ListInvoiceCommentsAndHistoryResponse

class TestListInvoiceCommentsAndHistoryResponse(unittest.TestCase):
    """ListInvoiceCommentsAndHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListInvoiceCommentsAndHistoryResponse:
        """Test ListInvoiceCommentsAndHistoryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListInvoiceCommentsAndHistoryResponse`
        """
        model = ListInvoiceCommentsAndHistoryResponse()
        if include_optional:
            return ListInvoiceCommentsAndHistoryResponse(
                code = 0,
                message = 'success',
                comments = [
                    ls_zoho_billing_invoices.models.list_invoice_comments_and_history_response_comments_inner.list_invoice_comments_and_history_response_comments_inner(
                        comment_id = '982000000567019', 
                        invoice_id = '903000000079426', 
                        description = 'Payment has been made for the invoice INV-384', 
                        commented_by_id = '982000000554041', 
                        commented_by = 'John David', 
                        comment_type = 'system', 
                        operation_type = 'Added', 
                        date = '2013-11-18', 
                        date_description = 'yesterday', 
                        time = '2:38 AM', 
                        transaction_id = '982000000567204', 
                        transaction_type = 'invoice', )
                    ]
            )
        else:
            return ListInvoiceCommentsAndHistoryResponse(
        )
        """

    def testListInvoiceCommentsAndHistoryResponse(self):
        """Test ListInvoiceCommentsAndHistoryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
