# coding: utf-8

"""
    Invoices

    Invoices describe how much a customer owes for his subscription. Invoices are created for recurring charges, one time charges including any prorated adjustments.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_invoices.models.add_items_to_a_pending_invoice_request import AddItemsToAPendingInvoiceRequest

class TestAddItemsToAPendingInvoiceRequest(unittest.TestCase):
    """AddItemsToAPendingInvoiceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddItemsToAPendingInvoiceRequest:
        """Test AddItemsToAPendingInvoiceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddItemsToAPendingInvoiceRequest`
        """
        model = AddItemsToAPendingInvoiceRequest()
        if include_optional:
            return AddItemsToAPendingInvoiceRequest(
                invoice_items = [
                    ls_zoho_billing_invoices.models.add_items_to_a_pending_invoice_request_invoice_items_inner.add_items_to_a_pending_invoice_request_invoice_items_inner(
                        code = UsageAddon, 
                        product_id = 90300000079226, 
                        name = usage charge, 
                        description = Usage charges for last month, 
                        price = 10, 
                        quantity = 1, 
                        tax_id = 90300000079226, 
                        tax_exemption_id = 90300000079226, )
                    ]
            )
        else:
            return AddItemsToAPendingInvoiceRequest(
        )
        """

    def testAddItemsToAPendingInvoiceRequest(self):
        """Test AddItemsToAPendingInvoiceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
