# coding: utf-8

"""
    Invoices

    Invoices describe how much a customer owes for his subscription. Invoices are created for recurring charges, one time charges including any prorated adjustments.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_invoices.models.list_all_invoices_response_invoices_inner import ListAllInvoicesResponseInvoicesInner

class TestListAllInvoicesResponseInvoicesInner(unittest.TestCase):
    """ListAllInvoicesResponseInvoicesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllInvoicesResponseInvoicesInner:
        """Test ListAllInvoicesResponseInvoicesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllInvoicesResponseInvoicesInner`
        """
        model = ListAllInvoicesResponseInvoicesInner()
        if include_optional:
            return ListAllInvoicesResponseInvoicesInner(
                invoice_id = '903000000079426',
                number = 'INV-384',
                status = 'paid',
                invoice_date = '2016-06-05',
                due_date = '2016-06-05',
                customer_id = '903000000000099',
                customer_name = 'Bowman Furniture',
                email = 'benjamin.george@bowmanfurniture.com',
                balance = 0,
                total = 370,
                currency_code = 'USD',
                currency_symbol = '$',
                has_attachment = true,
                created_time = '2016-06-05T02:15:15-0700',
                updated_time = '2016-06-05T02:15:15-0700'
            )
        else:
            return ListAllInvoicesResponseInvoicesInner(
        )
        """

    def testListAllInvoicesResponseInvoicesInner(self):
        """Test ListAllInvoicesResponseInvoicesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
