# coding: utf-8

"""
    Plans

    A plan object contains the billing and pricing information of a plan. Your organization may consist of plans that differ either by features or by the plan’s billing frequency. You can have a $10 basic plan, $20 professional plan, $24 monthly or a $240 yearly plan.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_plans.models.create_a_plan_request import CreateAPlanRequest

class TestCreateAPlanRequest(unittest.TestCase):
    """CreateAPlanRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAPlanRequest:
        """Test CreateAPlanRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAPlanRequest`
        """
        model = CreateAPlanRequest()
        if include_optional:
            return CreateAPlanRequest(
                plan_code = 'basic-monthly',
                name = 'Basic',
                recurring_price = 400,
                unit = 'kg',
                interval = 1,
                interval_unit = 'months',
                billing_cycles = -1,
                trial_period = 1,
                setup_fee = 100,
                setup_fee_account_id = '903000987009903',
                tags = [
                    ls_zoho_billing_plans.models.tags_inner.tags_inner(
                        tag_id = 460000000054182, 
                        tag_option_id = 460000000054280, )
                    ],
                custom_fields = [
                    ls_zoho_billing_plans.models.custom_fields_inner.custom_fields_inner(
                        label = 'cfitem', 
                        value = 'Normal', )
                    ],
                product_id = '903000000045027',
                product_type = 'goods',
                hsn_or_sac = '74191010',
                sat_item_key_code = '71121206',
                unitkey_code = 'E48',
                item_tax_preferences = [
                    ls_zoho_billing_plans.models.item_tax_preferences_inner.item_tax_preferences_inner(
                        tax_specification = 'intra', 
                        tax_name = 'GST', 
                        tax_percentage = 10, 
                        tax_id = 'no tax will be associated', )
                    ],
                tax_id = 'no tax will be associated',
                is_taxable = 'true',
                tax_exemption_id = '903000006345',
                tax_exemption_code = 'GST FREE',
                description = 'Basic monthly plan.',
                store_markup_description = 'Mailbox Storage-100GB | User & Docs Storage-500GB | User',
                can_charge_setup_fee_immediately = True
            )
        else:
            return CreateAPlanRequest(
                plan_code = 'basic-monthly',
                name = 'Basic',
                recurring_price = 400,
                interval = 1,
                product_id = '903000000045027',
        )
        """

    def testCreateAPlanRequest(self):
        """Test CreateAPlanRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
