# coding: utf-8

"""
    Plans

    A plan object contains the billing and pricing information of a plan. Your organization may consist of plans that differ either by features or by the plan’s billing frequency. You can have a $10 basic plan, $20 professional plan, $24 monthly or a $240 yearly plan.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_plans.models.plan_response_tags_inner import PlanResponseTagsInner

class TestPlanResponseTagsInner(unittest.TestCase):
    """PlanResponseTagsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanResponseTagsInner:
        """Test PlanResponseTagsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanResponseTagsInner`
        """
        model = PlanResponseTagsInner()
        if include_optional:
            return PlanResponseTagsInner(
                tag_option_id = 460000000054280,
                is_tag_mandatory = 'false',
                tag_name = 'Colors',
                tag_id = 460000000054182,
                tag_option_name = 'Black'
            )
        else:
            return PlanResponseTagsInner(
        )
        """

    def testPlanResponseTagsInner(self):
        """Test PlanResponseTagsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
