# coding: utf-8

"""
    Plans

    A plan object contains the billing and pricing information of a plan. Your organization may consist of plans that differ either by features or by the plan’s billing frequency. You can have a $10 basic plan, $20 professional plan, $24 monthly or a $240 yearly plan.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_plans.models.update_a_plan_response_plan_custom_fields_inner import UpdateAPlanResponsePlanCustomFieldsInner

class TestUpdateAPlanResponsePlanCustomFieldsInner(unittest.TestCase):
    """UpdateAPlanResponsePlanCustomFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAPlanResponsePlanCustomFieldsInner:
        """Test UpdateAPlanResponsePlanCustomFieldsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAPlanResponsePlanCustomFieldsInner`
        """
        model = UpdateAPlanResponsePlanCustomFieldsInner()
        if include_optional:
            return UpdateAPlanResponsePlanCustomFieldsInner(
                customfield_id = '2000000029001',
                is_active = 'true',
                show_in_all_pdf = 'true',
                value_formatted = 'test',
                data_type = 'string',
                index = 1,
                label = 'cfitem',
                show_on_pdf = 'false',
                placeholder = 'cf_cfitem',
                value = 'test'
            )
        else:
            return UpdateAPlanResponsePlanCustomFieldsInner(
        )
        """

    def testUpdateAPlanResponsePlanCustomFieldsInner(self):
        """Test UpdateAPlanResponsePlanCustomFieldsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
