# coding: utf-8

"""
    Plans

    A plan object contains the billing and pricing information of a plan. Your organization may consist of plans that differ either by features or by the plan’s billing frequency. You can have a $10 basic plan, $20 professional plan, $24 monthly or a $240 yearly plan.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_plans.models.list_all_plans_response import ListAllPlansResponse

class TestListAllPlansResponse(unittest.TestCase):
    """ListAllPlansResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllPlansResponse:
        """Test ListAllPlansResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllPlansResponse`
        """
        model = ListAllPlansResponse()
        if include_optional:
            return ListAllPlansResponse(
                code = 0,
                message = 'success',
                plans = [
                    ls_zoho_billing_plans.models.list_all_plans_response_plans_inner.list_all_plans_response_plans_inner(
                        plan_code = 'basic-monthly', 
                        name = 'Basic', 
                        recurring_price = 400, 
                        unit = 'kg', 
                        interval = 1, 
                        interval_unit = 'months', 
                        billing_cycles = -1, 
                        trial_period = 0, 
                        setup_fee = 0, 
                        setup_fee_account_id = '903000987009903', 
                        setup_fee_account_name = 'General Income', 
                        product_id = '903000000045027', 
                        tax_id = 'no tax will be associated', 
                        product_type = 'goods', 
                        hsn_or_sac = '74191010', 
                        sat_item_key_code = '71121206', 
                        unitkey_code = 'E48', 
                        item_tax_preferences = [
                            ls_zoho_billing_plans.models.item_tax_preferences_inner.item_tax_preferences_inner(
                                tax_specification = 'intra', 
                                tax_name = 'GST', 
                                tax_percentage = 10, )
                            ], 
                        description = 'Basic monthly plan.', 
                        store_markup_description = 'Mailbox Storage-100GB | User & Docs Storage-500GB | User', 
                        status = 'active', 
                        addons = [
                            ls_zoho_billing_plans.models.list_all_plans_response_plans_inner_addons_inner.list_all_plans_response_plans_inner_addons_inner(
                                addon_code = 'Email-basic', )
                            ], 
                        created_time = '2016-06-05T17:40:49-0700', 
                        updated_time = '2016-06-05T24:40:49-0700', )
                    ]
            )
        else:
            return ListAllPlansResponse(
        )
        """

    def testListAllPlansResponse(self):
        """Test ListAllPlansResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
