# coding: utf-8

"""
    Payments

    A payment object describes details regarding a particular customer payment. There can be multiple payments for a single invoice. Multiple invoices can be paid in a single payment as well.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PaymentResponseAutotransaction(BaseModel):
    """
    If the payment mode is <code>autotransaction</code>, autotransaction information will be displayed in the autotransaction object. It contains <code>autotransaction_id</code>, <code>payment_gateway</code>, <code>gateway_transaction_id</code>, <code>card_id</code>, <code>last_four_digits</code>, <code>expiry_month</code> and <code>expiry_year</code>.
    """ # noqa: E501
    autotransaction_id: Optional[StrictStr] = Field(default=None, description="Auto-transaction ID generated for the payment made.")
    payment_gateway: Optional[StrictStr] = Field(default=None, description="Name of the payment gateway associated with payment.")
    gateway_transaction_id: Optional[StrictStr] = Field(default=None, description="Transaction ID provided by the gateway for the transaction.")
    gateway_error_message: Optional[StrictStr] = Field(default=None, description="Gateway error message for a failed transaction.")
    card_id: Optional[StrictStr] = Field(default=None, description="Card ID of the card associated with the transaction.")
    last_four_digits: Optional[StrictInt] = Field(default=None, description="Last four digits of the card.")
    expiry_month: Optional[StrictInt] = Field(default=None, description="Expiry month of the card.")
    expiry_year: Optional[StrictInt] = Field(default=None, description="Expiry year of the card.")
    __properties: ClassVar[List[str]] = ["autotransaction_id", "payment_gateway", "gateway_transaction_id", "gateway_error_message", "card_id", "last_four_digits", "expiry_month", "expiry_year"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentResponseAutotransaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentResponseAutotransaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "autotransaction_id": obj.get("autotransaction_id"),
            "payment_gateway": obj.get("payment_gateway"),
            "gateway_transaction_id": obj.get("gateway_transaction_id"),
            "gateway_error_message": obj.get("gateway_error_message"),
            "card_id": obj.get("card_id"),
            "last_four_digits": obj.get("last_four_digits"),
            "expiry_month": obj.get("expiry_month"),
            "expiry_year": obj.get("expiry_year")
        })
        return _obj


