# coding: utf-8

"""
    Products

    A product refers to the service you offer your customers. There can be multiple products created if you offer more than one service. Each product can have different plans and addons associated with it.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ProductResponse(BaseModel):
    """
    ProductResponse
    """ # noqa: E501
    product_id: Optional[StrictStr] = Field(default=None, description="Unique ID generated by the server for the product.")
    name: Optional[StrictStr] = Field(default=None, description="Name of your choice to be displayed in the interface.")
    description: Optional[StrictStr] = Field(default=None, description="Short description regarding the product.")
    email_ids: Optional[StrictStr] = Field(default=None, description="The email IDs to which notifications related to the product need to be sent. (Use comma separation for multiple email-ids)")
    redirect_url: Optional[StrictStr] = Field(default=None, description="The URL to which customers should be redirected to once they subscribe to the product.")
    status: Optional[StrictStr] = Field(default=None, description="Status of the product. It can be <code>active</code> or <code>inactive</code>")
    created_time: Optional[StrictStr] = Field(default=None, description="The time at which the product was created.")
    updated_time: Optional[StrictStr] = Field(default=None, description="The time at which the product details were last updated.")
    __properties: ClassVar[List[str]] = ["product_id", "name", "description", "email_ids", "redirect_url", "status", "created_time", "updated_time"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProductResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProductResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "product_id": obj.get("product_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "email_ids": obj.get("email_ids"),
            "redirect_url": obj.get("redirect_url"),
            "status": obj.get("status"),
            "created_time": obj.get("created_time"),
            "updated_time": obj.get("updated_time")
        })
        return _obj


