# coding: utf-8

"""
    Credit-Notes

    Credit notes are created when a refund is to be made to a customer. A credit note object allows you to keep track of all credit note related information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_credit_notes.models.delete_a_credit_note_response import DeleteACreditNoteResponse

class TestDeleteACreditNoteResponse(unittest.TestCase):
    """DeleteACreditNoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteACreditNoteResponse:
        """Test DeleteACreditNoteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteACreditNoteResponse`
        """
        model = DeleteACreditNoteResponse()
        if include_optional:
            return DeleteACreditNoteResponse(
                code = 0,
                message = 'The credit note has been deleted.'
            )
        else:
            return DeleteACreditNoteResponse(
        )
        """

    def testDeleteACreditNoteResponse(self):
        """Test DeleteACreditNoteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
