# coding: utf-8

"""
    Settings

    Tax Settings Related APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ls_zoho_billing_settings.models.retrieve_list_of_tax_exemptions_response_tax_exemptions_inner import RetrieveListOfTaxExemptionsResponseTaxExemptionsInner
from typing import Optional, Set
from typing_extensions import Self

class RetrieveListOfTaxExemptionsResponse(BaseModel):
    """
    RetrieveListOfTaxExemptionsResponse
    """ # noqa: E501
    code: Optional[StrictInt] = None
    message: Optional[StrictStr] = None
    tax_exemptions: Optional[List[RetrieveListOfTaxExemptionsResponseTaxExemptionsInner]] = None
    __properties: ClassVar[List[str]] = ["code", "message", "tax_exemptions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetrieveListOfTaxExemptionsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "code",
            "message",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tax_exemptions (list)
        _items = []
        if self.tax_exemptions:
            for _item_tax_exemptions in self.tax_exemptions:
                if _item_tax_exemptions:
                    _items.append(_item_tax_exemptions.to_dict())
            _dict['tax_exemptions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetrieveListOfTaxExemptionsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "message": obj.get("message"),
            "tax_exemptions": [RetrieveListOfTaxExemptionsResponseTaxExemptionsInner.from_dict(_item) for _item in obj["tax_exemptions"]] if obj.get("tax_exemptions") is not None else None
        })
        return _obj


