# coding: utf-8

"""
    Settings

    Tax Settings Related APIs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ls_zoho_billing_settings.models.churn_messages_inner import ChurnMessagesInner
from typing import Optional, Set
from typing_extensions import Self

class RetrieveChurnMessagePreferencesResponseChurnMessagesSettings(BaseModel):
    """
    RetrieveChurnMessagePreferencesResponseChurnMessagesSettings
    """ # noqa: E501
    is_advanced_version: Optional[StrictStr] = Field(default=None, description="Boolean to denote if it is an Simple version or Advanced Version.")
    is_reason_mandatory: Optional[StrictStr] = Field(default=None, description="Whether reason is mandatory or not.")
    churn_messages: Optional[List[ChurnMessagesInner]] = Field(default=None, description="List of Cancellation reasons")
    __properties: ClassVar[List[str]] = ["is_advanced_version", "is_reason_mandatory", "churn_messages"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetrieveChurnMessagePreferencesResponseChurnMessagesSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in churn_messages (list)
        _items = []
        if self.churn_messages:
            for _item_churn_messages in self.churn_messages:
                if _item_churn_messages:
                    _items.append(_item_churn_messages.to_dict())
            _dict['churn_messages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetrieveChurnMessagePreferencesResponseChurnMessagesSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "is_advanced_version": obj.get("is_advanced_version"),
            "is_reason_mandatory": obj.get("is_reason_mandatory"),
            "churn_messages": [ChurnMessagesInner.from_dict(_item) for _item in obj["churn_messages"]] if obj.get("churn_messages") is not None else None
        })
        return _obj


