# coding: utf-8

"""
    Time Entries

    Time entries are various entries of time made by users in a project, based on the time they spent on a project, in a task.<br><br><b>Possible error codes: </b><br><table><thead><tr><th>Error Code</th><th>Message</th></tr></thead><tbody><tr><td><span style=\"color:#FF0000;\"> 1002</span></td><td>This task does not exist in this project. Hence, this timesheet entry cannot be made</td></tr><tr><td><span style=\"color:#FF0000;\"> 20050</span></td><td>This timesheet entry is already being timed</td></tr><tr><td><span style=\"color:#FF0000;\"> 20054</span></td><td>This timesheet is being timed. Hence, it cannot be edited</td></tr></tbody></table>

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_time_entries.models.update_time_entry_response import UpdateTimeEntryResponse

class TestUpdateTimeEntryResponse(unittest.TestCase):
    """UpdateTimeEntryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateTimeEntryResponse:
        """Test UpdateTimeEntryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTimeEntryResponse`
        """
        model = UpdateTimeEntryResponse()
        if include_optional:
            return UpdateTimeEntryResponse(
                code = 0,
                message = 'The timesheet's information has been updated.',
                time_entry = ls_zoho_billing_time_entries.models.update_time_entry_response_time_entry.update_time_entry_response_time_entry(
                    time_entry_id = '460000000044021', 
                    project_id = '460000000044019', 
                    project_name = 'REAL TIME TRAFFIC FLUX', 
                    customer_id = '460000000044001', 
                    customer_name = 'SAF Instruments Inc', 
                    task_id = '460000000044009', 
                    task_name = 'Distribution Analysis', 
                    user_id = '460000000024003', 
                    user_name = 'John David', 
                    is_current_user = True, 
                    log_date = '2013-09-17', 
                    begin_time = '03:00', 
                    end_time = '04:00', 
                    log_time = '05:00', 
                    is_billable = True, 
                    billed_status = 'unbilled', 
                    invoice_id = '', 
                    notes = ' ', 
                    timer_started_at = ' ', 
                    timer_started_at_utc_time = '', 
                    timer_duration_in_minutes = ' ', 
                    timer_duration_in_seconds = '', 
                    created_time = '2013-09-11T18:05:27+0530', 
                    timesheet_custom_fields = '', )
            )
        else:
            return UpdateTimeEntryResponse(
        )
        """

    def testUpdateTimeEntryResponse(self):
        """Test UpdateTimeEntryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
