# coding: utf-8

"""
    Addons

    An addon contains additional features that are not part of the subscribed plan, but are made available to customers on purchase of the addon. There are two kinds of addons - one-time and recurring. For a one-time addon, customers pay only once at the time of subscription, whereas for a recurring addon, customers have to pay for the addon each time they pay for the plan’s subscription. An addon can be associated with one or more plans of a product.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_addons.models.update_an_addon_request import UpdateAnAddonRequest

class TestUpdateAnAddonRequest(unittest.TestCase):
    """UpdateAnAddonRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAnAddonRequest:
        """Test UpdateAnAddonRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAnAddonRequest`
        """
        model = UpdateAnAddonRequest()
        if include_optional:
            return UpdateAnAddonRequest(
                addon_code = 'Email-basic',
                name = 'Email addon',
                unit_name = 'Email',
                pricing_scheme = 'unit',
                price_brackets = [
                    ls_zoho_billing_addons.models.update_an_addon_request_price_brackets_inner.update_an_addon_request_price_brackets_inner(
                        start_quantity = 1, 
                        end_quantity = 50, 
                        price = 10, )
                    ],
                type = 'recurring',
                interval_unit = 'monthly',
                tags = [
                    ls_zoho_billing_addons.models.update_an_addon_request_tags_inner.update_an_addon_request_tags_inner(
                        tag_id = 460000000054182, 
                        tag_option_id = 460000000054278, )
                    ],
                custom_fields = [
                    ls_zoho_billing_addons.models.custom_fields_inner.custom_fields_inner(
                        label = 'cfitem', 
                        value = 'test', )
                    ],
                applicable_to_all_plans = False,
                plans = [
                    ls_zoho_billing_addons.models.update_an_addon_request_plans_inner.update_an_addon_request_plans_inner(
                        plan_code = 'basic-monthly', 
                        name = Basic, )
                    ],
                product_id = '903000000045027',
                description = 'The addon for additonal email support',
                store_markup_description = 'Mailbox Storage-100GB | User & Docs Storage-500GB | User',
                product_type = 'goods',
                hsn_or_sac = '74191010',
                sat_item_key_code = '10128918',
                unitkey_code = 'Yh7',
                item_tax_preferences = [
                    ls_zoho_billing_addons.models.item_tax_preferences_inner.item_tax_preferences_inner(
                        tax_specification = 'intra', 
                        tax_name = 'GST', 
                        tax_percentage = 10, 
                        tax_id = 'no tax will be associated', )
                    ],
                tax_id = 'no tax will be associated',
                tax_exemption_id = '903000006345',
                tax_exemption_code = 'GST FREE'
            )
        else:
            return UpdateAnAddonRequest(
                addon_code = 'Email-basic',
                name = 'Email addon',
                unit_name = 'Email',
                price_brackets = [
                    ls_zoho_billing_addons.models.update_an_addon_request_price_brackets_inner.update_an_addon_request_price_brackets_inner(
                        start_quantity = 1, 
                        end_quantity = 50, 
                        price = 10, )
                    ],
                plans = [
                    ls_zoho_billing_addons.models.update_an_addon_request_plans_inner.update_an_addon_request_plans_inner(
                        plan_code = 'basic-monthly', 
                        name = Basic, )
                    ],
                product_id = '903000000045027',
        )
        """

    def testUpdateAnAddonRequest(self):
        """Test UpdateAnAddonRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
