openapi: 3.0.0
info:
  title: Quotes
  description: 'A quote is an approximation, of the prices, which a seller projects to a buyer. There can be different quotes to different buyers.<br><br><b>Possible error codes: </b><br><table><thead><tr><th>Error Code</th><th>Message</th></tr></thead><tbody><tr><td><span style="color:#FF0000;"> 1001</span></td><td>Quote Number already exist</td></tr><tr><td><span style="color:#FF0000;"> 1002</span></td><td>Quote does not exist</td></tr><td><span style="color:#FF0000;"> 2007</span></td><td>Quot[...]'
  contact: {}
  version: 1.0.0
servers:
  -
    url: 'https://www.zohoapis.com/billing/v1'
    description: 'API Endpoint'
tags:
  -
    name: quotes
    description: 'Quotes Module'
paths:
  /estimates:
    post:
      tags:
        - estimates
      summary: 'Create a Quote'
      description: 'Create a quote for your customer.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.CREATE
    get:
      tags:
        - estimates
      summary: 'List Quotes'
      description: 'List all quotes with pagination.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.READ
  '/estimates/{estimate_id}':
    put:
      tags:
        - estimates
      summary: 'Update a Quote'
      description: 'Update an existing quote. To delete a line item just remove it from the line_items list.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.UPDATE
    get:
      tags:
        - estimates
      summary: 'Retrieve a Quote'
      description: 'Fetch the details of a quote.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.READ
    delete:
      tags:
        - estimates
      summary: 'Delete a Quote'
      description: 'Delete an existing quote.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.DELETE
  '/estimates/{estimate_id}/status/sent':
    post:
      tags:
        - estimates
      summary: 'Mark a Quote as sent'
      description: 'Mark a draft quote as sent.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.CREATE
  '/estimates/{estimate_id}/status/accepted':
    post:
      tags:
        - estimates
      summary: 'Mark a Quote as accepted'
      description: 'Mark a sent quote as accepted if the customer has accepted it.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.CREATE
  '/estimates/{estimate_id}/status/declined':
    post:
      tags:
        - estimates
      summary: 'Mark a Quote as declined'
      description: 'Mark a sent quote as declined if the customer has rejected it.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.CREATE
  '/estimates/{estimate_id}/email':
    post:
      tags:
        - estimates
      summary: 'Email a quote'
      description: 'Email a quote to the customer. Input json string is not mandatory. If input json string is empty, mail will be send with default mail content.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.CREATE
    get:
      tags:
        - estimates
      summary: 'Get quote email content'
      description: 'Get the email content of a Quote.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.READ
  /estimates/email:
    post:
      tags:
        - estimates
      summary: 'Email multiple quotes'
      description: 'Send quotes to your customers by email. Maximum of 10 quotes can be sent at once.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.CREATE
  /estimates/pdf:
    get:
      tags:
        - estimates
      summary: 'Bulk export quotes'
      description: 'Maximum of 25 quotes can be exported in a single pdf.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.READ
  /estimates/print:
    get:
      tags:
        - estimates
      summary: 'Bulk print Quotes'
      description: 'Export Quotes as pdf and print them. Maximum of 25 quotes can be printed.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.READ
  /estimates/templates:
    get:
      tags:
        - estimates
      summary: 'List quote templates'
      description: 'Get all quote pdf templates.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.READ
  '/estimates/{estimate_id}/templates/{template_id}':
    put:
      tags:
        - estimates
      summary: 'Update quote template'
      description: 'Update the pdf template associated with the quote.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.UPDATE
  '/estimates/{estimate_id}/comments':
    get:
      tags:
        - estimates
      summary: 'List quote comments & history'
      description: 'Get the complete history and comments of a quote.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.READ
    post:
      tags:
        - estimates
      summary: 'Add Comments'
      description: 'Add a comment for a quote.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.CREATE
  '/estimates/{estimate_id}/comments/{comment_id}':
    put:
      tags:
        - estimates
      summary: 'Update comment'
      description: 'Update an existing comment of a quote.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.UPDATE
    delete:
      tags:
        - estimates
      summary: 'Delete a comment'
      description: 'Delete a quote comment.'
      deprecated: false
      security:
        -
          Zoho_Auth:
            - ZohoSubscriptions.quotes.DELETE
components:
  securitySchemes:
    Zoho_Auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth'
          scopes:
            ZohoSubscriptions.quotes.CREATE: 'Create Quotes'
            ZohoSubscriptions.quotes.UPDATE: 'Update Quotes'
            ZohoSubscriptions.quotes.READ: 'Read Quotes'
            ZohoSubscriptions.quotes.DELETE: 'Delete Quotes'
