# coding: utf-8

"""
    Plans

    A plan object contains the billing and pricing information of a plan. Your organization may consist of plans that differ either by features or by the plan’s billing frequency. You can have a $10 basic plan, $20 professional plan, $24 monthly or a $240 yearly plan.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ItemTaxPreferencesInner(BaseModel):
    """
    ItemTaxPreferencesInner
    """ # noqa: E501
    tax_specification: Optional[StrictStr] = Field(default=None, description="Tax specification for the plan. It can be either <code>inter</code> or <code>intra</code>.")
    tax_name: Optional[StrictStr] = Field(default=None, description="Name of the tax to which subscription is associated.")
    tax_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Percentage of tax applied to the plan/addon")
    tax_id: Optional[StrictStr] = Field(default='no tax will be associated', description="Tax ID to which you would like to associate with this plan.")
    __properties: ClassVar[List[str]] = ["tax_specification", "tax_name", "tax_percentage", "tax_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ItemTaxPreferencesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ItemTaxPreferencesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tax_specification": obj.get("tax_specification"),
            "tax_name": obj.get("tax_name"),
            "tax_percentage": obj.get("tax_percentage"),
            "tax_id": obj.get("tax_id") if obj.get("tax_id") is not None else 'no tax will be associated'
        })
        return _obj


