# coding: utf-8

"""
    Hosted-Pages

    Zoho Billing provides a hosted payment page to integrate with your websites. You can securely integrate with Zoho Billing for collecting your customer's sensitive card information through the hosted page. These Hosted Pages will expire within one hour.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_hosted_pages.models.add_payment_method_for_a_customer_response_hostedpage import AddPaymentMethodForACustomerResponseHostedpage

class TestAddPaymentMethodForACustomerResponseHostedpage(unittest.TestCase):
    """AddPaymentMethodForACustomerResponseHostedpage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddPaymentMethodForACustomerResponseHostedpage:
        """Test AddPaymentMethodForACustomerResponseHostedpage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddPaymentMethodForACustomerResponseHostedpage`
        """
        model = AddPaymentMethodForACustomerResponseHostedpage()
        if include_optional:
            return AddPaymentMethodForACustomerResponseHostedpage(
                hostedpage_id = '8c589071e7e26a8d28e8af081c373fb00bd6dc5366fd129eefd5c61c569da526',
                status = 'success',
                url = 'https://billing.zoho.com/hostedpage/2-8c589071e7e26a8d28e8af081c373fb00bd6dc5366fd129eefd5c61c569da526/checkout',
                action = Update payment method,
                expiring_time = '2016-06-05T00:11:16-0700',
                created_time = '2016-06-05T23:10:16-0700',
                custom_fields = [
                    ls_zoho_billing_hosted_pages.models.buy_one_time_addon_for_a_subscription_response_hostedpage_custom_fields_inner.buy_one_time_addon_for_a_subscription_response_hostedpage_custom_fields_inner(
                        index = 1, 
                        value = '', 
                        label = '', 
                        data_type = 'string', )
                    ]
            )
        else:
            return AddPaymentMethodForACustomerResponseHostedpage(
        )
        """

    def testAddPaymentMethodForACustomerResponseHostedpage(self):
        """Test AddPaymentMethodForACustomerResponseHostedpage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
