# coding: utf-8

"""
    Hosted-Pages

    Zoho Billing provides a hosted payment page to integrate with your websites. You can securely integrate with Zoho Billing for collecting your customer's sensitive card information through the hosted page. These Hosted Pages will expire within one hour.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_hosted_pages.models.item_custom_fields_inner import ItemCustomFieldsInner

class TestItemCustomFieldsInner(unittest.TestCase):
    """ItemCustomFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemCustomFieldsInner:
        """Test ItemCustomFieldsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemCustomFieldsInner`
        """
        model = ItemCustomFieldsInner()
        if include_optional:
            return ItemCustomFieldsInner(
                label = '',
                value = ''
            )
        else:
            return ItemCustomFieldsInner(
        )
        """

    def testItemCustomFieldsInner(self):
        """Test ItemCustomFieldsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
