# coding: utf-8

"""
    Hosted-Pages

    Zoho Billing provides a hosted payment page to integrate with your websites. You can securely integrate with Zoho Billing for collecting your customer's sensitive card information through the hosted page. These Hosted Pages will expire within one hour.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_hosted_pages.models.update_card_for_a_subscription_request import UpdateCardForASubscriptionRequest

class TestUpdateCardForASubscriptionRequest(unittest.TestCase):
    """UpdateCardForASubscriptionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCardForASubscriptionRequest:
        """Test UpdateCardForASubscriptionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCardForASubscriptionRequest`
        """
        model = UpdateCardForASubscriptionRequest()
        if include_optional:
            return UpdateCardForASubscriptionRequest(
                subscription_id = '9030000079200',
                redirect_url = 'http://www.zillum.com/products/piperhost',
                payment_gateways = [
                    ls_zoho_billing_hosted_pages.models.payment_gateways_inner.payment_gateways_inner(
                        payment_gateway = 'payflow_pro', )
                    ]
            )
        else:
            return UpdateCardForASubscriptionRequest(
                subscription_id = '9030000079200',
        )
        """

    def testUpdateCardForASubscriptionRequest(self):
        """Test UpdateCardForASubscriptionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
