# coding: utf-8

"""
    Contact-Persons

    A contact person is customer’s additional point of contact.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ls_zoho_billing_contact_persons.models.list_of_all_contact_persons_response import ListOfAllContactPersonsResponse

class TestListOfAllContactPersonsResponse(unittest.TestCase):
    """ListOfAllContactPersonsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListOfAllContactPersonsResponse:
        """Test ListOfAllContactPersonsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListOfAllContactPersonsResponse`
        """
        model = ListOfAllContactPersonsResponse()
        if include_optional:
            return ListOfAllContactPersonsResponse(
                code = 0,
                message = 'success',
                contact_persons = [
                    ls_zoho_billing_contact_persons.models.list_of_all_contact_persons_response_contact_persons_inner.list_of_all_contact_persons_response_contact_persons_inner(
                        contactperson_id = '903000000053362', 
                        first_name = 'Mark', 
                        last_name = 'Cruizer', 
                        email = 'mark.cruzer@bowmanfurniture.com', 
                        mobile = '786663728', 
                        phone = '0417254482', )
                    ]
            )
        else:
            return ListOfAllContactPersonsResponse(
        )
        """

    def testListOfAllContactPersonsResponse(self):
        """Test ListOfAllContactPersonsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
