# coding: utf-8

# flake8: noqa

"""
    Customers

    A customer object allows you to keep track of all customer related information.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CustomersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BillingAddress",
    "CreateACustomerRequest",
    "CreateACustomerRequestCustomFieldsInner",
    "CreateACustomerResponse",
    "CustomFieldsInner",
    "CustomerResponse",
    "CustomerResponseCustomFieldsInner",
    "CustomerResponseDefaultTemplates",
    "CustomerResponseDocumentsInner",
    "CustomerResponseTagsInner",
    "DefaultTemplates",
    "DeleteACustomerResponse",
    "ListAllCustomersResponse",
    "ListAllCustomersResponseCustomersInner",
    "ListOfTransactionsResponse",
    "ListOfTransactionsResponseTransactionsInner",
    "MarkAsActiveResponse",
    "MarkAsInactiveResponse",
    "RetrieveACustomerResponse",
    "RetrieveACustomerResponseCustomer",
    "RetrieveACustomerUsingCrmReferenceResponse",
    "RetrieveACustomerUsingCrmReferenceResponseCustomer",
    "ShippingAddress",
    "TagsInner",
    "UpdateACustomerRequest",
    "UpdateACustomerRequestCustomFieldsInner",
    "UpdateACustomerResponse",
    "UpdateACustomerResponseCustomer",
    "UpdateACustomerResponseCustomerDefaultTemplatesInner",
]

# import apis into sdk package
from ls_zoho_billing_customers.api.customers_api import CustomersApi as CustomersApi

# import ApiClient
from ls_zoho_billing_customers.api_response import ApiResponse as ApiResponse
from ls_zoho_billing_customers.api_client import ApiClient as ApiClient
from ls_zoho_billing_customers.configuration import Configuration as Configuration
from ls_zoho_billing_customers.exceptions import OpenApiException as OpenApiException
from ls_zoho_billing_customers.exceptions import ApiTypeError as ApiTypeError
from ls_zoho_billing_customers.exceptions import ApiValueError as ApiValueError
from ls_zoho_billing_customers.exceptions import ApiKeyError as ApiKeyError
from ls_zoho_billing_customers.exceptions import ApiAttributeError as ApiAttributeError
from ls_zoho_billing_customers.exceptions import ApiException as ApiException

# import models into sdk package
from ls_zoho_billing_customers.models.billing_address import BillingAddress as BillingAddress
from ls_zoho_billing_customers.models.create_a_customer_request import CreateACustomerRequest as CreateACustomerRequest
from ls_zoho_billing_customers.models.create_a_customer_request_custom_fields_inner import CreateACustomerRequestCustomFieldsInner as CreateACustomerRequestCustomFieldsInner
from ls_zoho_billing_customers.models.create_a_customer_response import CreateACustomerResponse as CreateACustomerResponse
from ls_zoho_billing_customers.models.custom_fields_inner import CustomFieldsInner as CustomFieldsInner
from ls_zoho_billing_customers.models.customer_response import CustomerResponse as CustomerResponse
from ls_zoho_billing_customers.models.customer_response_custom_fields_inner import CustomerResponseCustomFieldsInner as CustomerResponseCustomFieldsInner
from ls_zoho_billing_customers.models.customer_response_default_templates import CustomerResponseDefaultTemplates as CustomerResponseDefaultTemplates
from ls_zoho_billing_customers.models.customer_response_documents_inner import CustomerResponseDocumentsInner as CustomerResponseDocumentsInner
from ls_zoho_billing_customers.models.customer_response_tags_inner import CustomerResponseTagsInner as CustomerResponseTagsInner
from ls_zoho_billing_customers.models.default_templates import DefaultTemplates as DefaultTemplates
from ls_zoho_billing_customers.models.delete_a_customer_response import DeleteACustomerResponse as DeleteACustomerResponse
from ls_zoho_billing_customers.models.list_all_customers_response import ListAllCustomersResponse as ListAllCustomersResponse
from ls_zoho_billing_customers.models.list_all_customers_response_customers_inner import ListAllCustomersResponseCustomersInner as ListAllCustomersResponseCustomersInner
from ls_zoho_billing_customers.models.list_of_transactions_response import ListOfTransactionsResponse as ListOfTransactionsResponse
from ls_zoho_billing_customers.models.list_of_transactions_response_transactions_inner import ListOfTransactionsResponseTransactionsInner as ListOfTransactionsResponseTransactionsInner
from ls_zoho_billing_customers.models.mark_as_active_response import MarkAsActiveResponse as MarkAsActiveResponse
from ls_zoho_billing_customers.models.mark_as_inactive_response import MarkAsInactiveResponse as MarkAsInactiveResponse
from ls_zoho_billing_customers.models.retrieve_a_customer_response import RetrieveACustomerResponse as RetrieveACustomerResponse
from ls_zoho_billing_customers.models.retrieve_a_customer_response_customer import RetrieveACustomerResponseCustomer as RetrieveACustomerResponseCustomer
from ls_zoho_billing_customers.models.retrieve_a_customer_using_crm_reference_response import RetrieveACustomerUsingCrmReferenceResponse as RetrieveACustomerUsingCrmReferenceResponse
from ls_zoho_billing_customers.models.retrieve_a_customer_using_crm_reference_response_customer import RetrieveACustomerUsingCrmReferenceResponseCustomer as RetrieveACustomerUsingCrmReferenceResponseCustomer
from ls_zoho_billing_customers.models.shipping_address import ShippingAddress as ShippingAddress
from ls_zoho_billing_customers.models.tags_inner import TagsInner as TagsInner
from ls_zoho_billing_customers.models.update_a_customer_request import UpdateACustomerRequest as UpdateACustomerRequest
from ls_zoho_billing_customers.models.update_a_customer_request_custom_fields_inner import UpdateACustomerRequestCustomFieldsInner as UpdateACustomerRequestCustomFieldsInner
from ls_zoho_billing_customers.models.update_a_customer_response import UpdateACustomerResponse as UpdateACustomerResponse
from ls_zoho_billing_customers.models.update_a_customer_response_customer import UpdateACustomerResponseCustomer as UpdateACustomerResponseCustomer
from ls_zoho_billing_customers.models.update_a_customer_response_customer_default_templates_inner import UpdateACustomerResponseCustomerDefaultTemplatesInner as UpdateACustomerResponseCustomerDefaultTemplatesInner
