name: Generate clients
on: push
jobs:
  generate-clients:
    runs-on: ubuntu-latest
    name: Generate Python Client
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Install OpenAPI Generator CLI
      run: npm install -g @openapitools/openapi-generator-cli

    - name: Generate clients for each spec
      run: |
        for spec in specs/*.yml; do
          name=$(basename "$spec" .yml)
          outdir="python-client-$name"
          pkgname="ls_zoho_billing_$(echo "$name" | tr '-' '_')"
          openapi-generator-cli generate \
            -g python \
            -i "$spec" \
            -o "$outdir" \
            --additional-properties "packageName=$pkgname,projectName=$pkgname,packageVersion=1.0.0,packageDescription=Python client for Zoho Billing ($name),packageAuthor=Letstream,packageAuthorEmail=support@theletstream.com,packageUrl=https://www.theletstream.com?utm_source=github-zohobillingclient,licenseName=MIT,hideGenerationTimestamp=true"
        done

    - name: Commit new clients
      run: |
        git config --global user.name 'Letstream Bot'
        git config --global user.email 'support@theletstream.com'
        git add python-client-*/
        git commit -am "Update python clients"
        git push
