name: Generate clients
on: push
jobs:
  generate-clients:
    runs-on: ubuntu-latest
    name: Example
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Install
      run: >-
        python -m
        pip install -r requirements.txt
        --user

    - name: Install swagger-cli
      run: npm install -g swagger-cli

    - name: Merge OpenAPI specs
      run: |
        swagger-cli bundle specs/*.yml -o specs/openapi.yaml

    - name: Generate unified client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: python
        openapi-file: ./specs/openapi.yaml
        additional-properties: |
          packageName=ls_zoho_billing,
          projectName=ls-zoho-billing,
          packageVersion=1.0.0,
          packageDescription="Python client for Zoho Billing",
          packageAuthor="Letstream",
          packageAuthorEmail=support@theletstream.com,
          packageUrl="https://www.theletstream.com?utm_source=github-zohobillingclient",
          licenseName=MIT,
          hideGenerationTimestamp=true

    - name: Commit new client
      run: |
        git config --global user.name 'Letstream Bot'
        git config --global user.email 'support@theletstream.com'
        git add python-client/
        git commit -am "Update python client"
        git push
